### ISSUE TITLE
Unable to deploy Azure logic app (ZIP deploy)

### ISSUE THREAD

**Issue by Sahithi-Modak** [Azure/azure-cli-extensions#4063] opened 2021-11-03 09:39 UTC
## Describe the bug

**Command Name**
`az logicapp deployment source config-zip
Extension Name: logicapp. Version: 0.1.2.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\kd2204\.azure\cliextensions\logicapp\azext_logicapp\custom.py", line 1561, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "C:\Users\kd2204\.azure\cliextensions\logicapp\azext_logicapp\custom.py", line 1467, in remove_remote_build_app_settings
    scm_is_up_to_date = validate_app_settings_in_scm(
  File "C:\Users\kd2204\.azure\cliextensions\logicapp\azext_logicapp\custom.py", line 1426, in validate_app_settings_in_scm
    scm_settings = _get_app_settings_from_scm(cmd, resource_group_name, name, slot)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 75, in call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 71, in call
  File "C:\Users\kd2204\.azure\cliextensions\logicapp\azext_logicapp\custom.py", line 1416, in _get_app_settings_from_scm
    return response.json() or {}
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 900, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logicapp deployment source config-zip --name {} --resource-group {} --subscription {} --src {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2 *

Extensions:
logicapp 0.1.2

```

**Comment by yonzhan** [comment] 2021-11-03 09:42
route to service team

**Comment by archidda** [comment] 2021-11-08 22:53
@Sahithi-Modak  can you share output of your deploy command with "--debug" parameter?

**Comment by Sahithi-Modak** [comment] 2021-11-10 06:33
Hi @archidda 

I'm able to execute above command successfully but observed no workflow is deployed even though status is success.

cmd:

az logicapp deployment source config-zip --name testappworkflow  --resource-group *****--subscription "****" --src LogicAppDemo.zip
Output:

Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "ZipDeploy",
  "end_time": "2021-11-10T06:12:36.9441551Z",
  "id": "777c1eb0bdfa4500a80cb891b74864c0",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2021-11-10T06:12:36.9441551Z",
  "log_url": "https://testappworkflow.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "provisioningState": "Succeeded",
  "received_time": "2021-11-10T06:11:18.1325508Z",
  "site_name": "testappworkflow",
  "start_time": "2021-11-10T06:11:19.0522415Z",
  "status": 4,
  "status_text": "",
  "url": "https://testappworkflow.scm.azurewebsites.net/api/deployments/latest"
}

**Comment by Sahithi-Modak** [comment] 2021-11-10 06:39
Please find attached zip file,

Please let me know if i need to change anything.









[X]<https://modak.com/>

Tekumalla Sahithi

Senior Software Engineer | Modak Analytics LLP

M: +91 9059004642

E: ***@***.******@***.***>

www.modak.com<http://www.modak.com/>

[X]<https://www.facebook.com/ModakData/>

[X]<https://twitter.com/ModakAnalytics>

[X]<https://www.linkedin.com/company/modak/about/>







________________________________

**Comment by Sahithi-Modak** [comment] 2021-11-10 06:41
Please find attached zip file,

Please let me know if i need to change anything.

**Comment by archidda** [comment] 2021-11-10 17:19
Can you confirm if you zip file directly contains the workflow folders and root level artifacts like connections.json.

Take a look at the importat note highlighted in blue here-
https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-create-deploy-workflows?tabs=azure-cli#deploy-logic-app

Can you share your zip file for me to take a look? (Please sanitize if it has any secrets)

**Comment by Sahithi-Modak** [comment] 2021-11-10 17:21
Hello,


Please find attached zip file,



Thanks
________________________________

**Comment by Sahithi-Modak** [comment] 2021-11-10 17:23
@archidda 

i have attached the zip file, it is not showing here, i hope you have received the zip file.

please let me know if you need anything.

**Comment by archidda** [comment] 2021-11-10 18:37
I do not see the zip file attachment. Can you email it to me at archidda@microsoft.com

**Comment by archidda** [comment] 2021-11-11 18:09
@Sahithi-Modak I reviewed your zip file and it is not organized correctly. The zip file needs to contain the root level folders and files directly.

Currently, you have
sampleLogicApp.zip
    -> SampleLogicApp
        -> Stateful
        -> host.json
        -> local.settings.json

Instead, it should be 
sampleLogicApp.zip
    -> Stateful
    -> host.json
    -> local.settings.json

Note- uploading local.settings.json won't upload your app settings, that file is meant for local use only.

**Comment by archidda** [comment] 2021-11-11 18:24
Sharing this file(v22.zip) that I sometimes use for testing and works for me. I noticed you are missing a connections.json file in your zip as well. Not 100% sure if that makes the difference, but I would add and test.

**Comment by Sahithi-Modak** [comment] 2021-11-11 18:27
Archidda,


I haven’t received any zip file and I guess the file was not attached.

It would be helpful if you resend v22.zip file?

Thanks
________________________________

**Comment by archidda** [comment] 2021-11-12 17:12
I sent it again over email thread where you shared your Zip file.

**Comment by Sahithi-Modak** [comment] 2021-11-12 17:14
Thanks Arjun,


You can mark this issue as resolved.
It is working as expected.

Once again
thankyou so much for such quick response!!!


________________________________

**Comment by archidda** [comment] 2021-11-12 18:12
Cool, happy to help

**Comment by archidda** [comment] 2021-11-12 18:14
@yonzhan can you help close this issue?

**Closed** 2021-11-12 23:32 UTC
Labels: customer-reported, Logic App, Service Attention

**Comment by Sahithi-Modak** [comment] 2022-01-11 17:12
Hello @***@***.******@***.***>,

I tried to re-deploy the logic app with the following command; the deployment was successful, but I couldn't see any workflows in the Azure portal.

Command Used:


 az logicapp deployment source config-zip --name test-logicapp-23 --resource-group Humanatraining --subscription "Microsoft Partner Network" --src v22.zip


Output:


C:\workarea\Azure\logicapps\test> az logicapp deployment source config-zip --name test-logicapp-23 --resource-group Humanatraining --subscription "Microsoft Partner Network" --src v22.zip

Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "ZipDeploy",
  "end_time": "2022-01-11T17:07:46.4694597Z",
  "id": "ae7ff5ae37ff4b1b828c3e918777b719",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2022-01-11T17:07:46.4694597Z",
  "log_url": "https://test-logicapp-23.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "provisioningState": "Succeeded",
  "received_time": "2022-01-11T17:07:40.8435137Z",
  "site_name": "test-logicapp-23",
  "start_time": "2022-01-11T17:07:41.7809888Z",
  "status": 4,
  "status_text": "",
  "url": "https://test-logicapp-23.scm.azurewebsites.net/api/deployments/latest"
}





Please find attachment,


Could you please help us to resolve this?



Thanks,

Sahithi

________________________________

**Comment by archidda** [comment] 2022-01-12 03:15
Hey @Sahithi-Modak, can you tell me what changed since you last confirmed that issue was resolved on Nov 12, 2021 and now?
Also can you go to kudu and confirm if the files are present on the file system, here's how you check it- 
Portal-> logicapp -> Advanced Tools(under Development Tools) blade -> Click on "Go ->" -> Debug Console tab -> CMD -> Navigate to site/wwwroot.
Can you see the workflows uploaded from the zip file?

**Comment by Sahithi-Modak** [comment] 2022-01-12 04:57
Hello Arjun,

I've only added one more workflow this time, and that's all I've changed this time.
You previously given me a zip file with two workflows, so I just copied and pasted one of them with a different name.





Thanks,

Sahithi.

________________________________

**Comment by Sahithi-Modak** [comment] 2022-01-12 05:40
Hello Arjun,


In Portal-> logicapp -> Advanced Tools(under Development Tools) blade -> Click on "Go ->" -> Debug Console tab -> CMD -> Navigate to site/wwwroot.
I'm able to see all workflow related files.

[cid:6897b5e6-78ff-4913-8579-783a1c975a54]


Output:

C:\home\site\wwwroot>pwd

/c/home/site/wwwroot

C:\home\site\wwwroot>ls -ltr
total 3
-rw-r--r-- 1 Unknown+User Unknown+Group   2 Jan 11 17:41 parameters.json
-rw-r--r-- 1 Unknown+User Unknown+Group 151 Jan 11 22:51 host.json
-rw-r--r-- 1 Unknown+User Unknown+Group  28 Jan 11 22:51 connections.json
drwxr-xr-x 1 Unknown+User Unknown+Group   0 Jan 12 05:05 s1
drwxr-xr-x 1 Unknown+User Unknown+Group   0 Jan 12 05:05 s23
drwxr-xr-x 1 Unknown+User Unknown+Group   0 Jan 12 05:31 s32


Thanks,
Sahithi


________________________________

**Comment by archidda** [comment] 2022-01-12 18:54
okay that confirms the zip was deployed and unzipped successfully. It is not a CLI issue.

**Comment by archidda** [comment] 2022-01-12 21:01
Also can you share how you created the zip file?

**Comment by archidda** [comment] 2022-01-13 04:17
Can you try creating the zip using windows feature? 
Select files an folders -> Right click -> Send to -> Compressed(zipped) folder

I have seen a case in the past where there was an issue with the zip created using command. Lets see if that is the issue here, then we can debug and fix it.

**Comment by Sahithi-Modak** [comment] 2022-01-13 04:47
Hello Arjun,

I have tried creating zip using windows feature,
But still I'm facing same issue.

Thanks,
Sahithi.

________________________________

**Comment by archidda** [comment] 2022-01-13 17:57
Okay, thanks for trying that. Please share the zip file with me over email, I will take a look and try to reproduce the issue

**Comment by Sahithi-Modak** [comment] 2022-01-13 18:01
Hi Arjun,

I have sent the zip file to your mailing address.

Thanks
________________________________

**Comment by archidda** [comment] 2022-01-13 22:51
You zip is not correctly built. Pasting my previous comment for reference-

-------------------------------------------------------------------------------------------------------------------
archidda commented on Nov 11, 2021 • 
@Sahithi-Modak I reviewed your zip file and it is not organized correctly. The zip file needs to contain the root level folders and files directly.

Currently, you have
sampleLogicApp.zip
....-> SampleLogicApp
........-> Stateful
........-> host.json
........-> local.settings.json

Instead, it should be
sampleLogicApp.zip
....-> Stateful
....-> host.json
....-> local.settings.json

Note- uploading local.settings.json won't upload your app settings, that file is meant for local use only.

**Comment by archidda** [comment] 2022-01-13 23:09
After correcting the zip, I was able to load the workflows in my logicapp.

**Comment by Sahithi-Modak** [comment] 2022-01-15 13:43
Hi Arjun,

I have sent you the wrong zip file, please find the correct zip file.

Thanks,

**Comment by archidda** [comment] 2022-03-07 23:14
@Sahithi-Modak If you are still facing the issue with correct zip file, then this might be runtime issue and not CLI issue. Please create a support request from azure portal on logicapps team. That way we can help you better.

**Comment by riteshnus** [comment] 2023-03-16 10:23
Hello @archidda @Sahithi-Modak I am also facing same issue. Getting success in cli but no workflow created. So can you share the correct zip file or test zip file to use it. Thank you. My email is ritesh.nus@gmail.com
