### ISSUE TITLE
az image copy          : FAILURE.

### ISSUE THREAD

**Issue by rispoli** [Azure/azure-cli-extensions#1756] opened 2020-05-22 18:37 UTC
## Describe the bug

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.4.`

**Errors:**
```
Command '['/opt/az/bin/python3', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'Covid19_GPU_UCB_Centos7_os_disk_snapshot', '--resource-group', 'mockup', '--source', '/subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/MOCKUP/providers/Microsoft.Compute/disks/fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

Extensions:
image-copy-extension 0.2.4

```

**Comment by yonzhan** [comment] 2020-05-22 23:18
@qwordy please take a look

**Comment by qwordy** [comment] 2020-05-25 04:42
Hi, thanks for reporting this issue. Do you keep the source disk in the resource group? Image copy extension requires the source disk of image.

**Comment by rispoli** [comment] 2020-05-25 05:48
Hi, the original disk is in the resource group I'm trying to copy the image from:
![image](https://user-images.githubusercontent.com/2699595/82782075-c145a180-9e5b-11ea-868a-880985a5a8cd.png)
I can even manually create the snapshot, with the same name or a different one:
![image](https://user-images.githubusercontent.com/2699595/82782154-f05c1300-9e5b-11ea-9fca-58fe07358d7e.png)
but the automated procedure always fails at the automated snapshot creation stage.

Any other troubleshooting steps I might perform?

Thanks,
Daniele

**Comment by qwordy** [comment] 2020-05-26 02:09
That's quite interesting.
Could you try this command?
```
az snapshot create --name Covid19_GPU_UCB_Centos7_os_disk_snapshot --resource-group mockup --source /subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/MOCKUP/providers/Microsoft.Compute/disks/fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac
```

**Comment by rispoli** [comment] 2020-05-26 05:42
Unfortunately I get an error from that command:
`Resource fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac is not found.`
But the disk does exist:
![image](https://user-images.githubusercontent.com/2699595/82864274-7e9bcc00-9f24-11ea-9c6e-b23cf811c3d0.png)

**Comment by qwordy** [comment] 2020-05-27 02:08
Really?
What's result of this command?
```
az resource show --ids /subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/MOCKUP/providers/Microsoft.Compute/disks/fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac
```

**Comment by rispoli** [comment] 2020-05-27 05:50
`$ az resource show --ids /subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/MOCKUP/providers/Microsoft.Compute/disks/fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac
{
  "id": "/subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/MOCKUP/providers/Microsoft.Compute/disks/fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac",
  "identity": null,
  "kind": null,
  "location": "westeurope",
  "managedBy": "/subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/resourceGroups/mockup/providers/Microsoft.Compute/virtualMachines/fragmdgpu",
  "name": "fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac",
  "plan": null,
  "properties": {
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/Subscriptions/2a71c52b-0900-4357-ba64-0366b1c6e969/Providers/Microsoft.Compute/Locations/westeurope/Publishers/OpenLogic/ArtifactTypes/VMImage/Offers/CentOS/Skus/7.7/Versions/7.7.2020042900"
      }
    },
    "diskIOPSReadWrite": 120,
    "diskMBpsReadWrite": 25,
    "diskSizeBytes": 32212254720,
    "diskSizeGB": 30,
    "diskState": "Reserved",
    "encryption": {
      "type": "EncryptionAtRestWithPlatformKey"
    },
    "hyperVGeneration": "V1",
    "networkAccessPolicy": "AllowAll",
    "osType": "Linux",
    "provisioningState": "Succeeded",
    "timeCreated": "2020-05-13T10:43:48.5805498+00:00",
    "uniqueId": "121312e4-6bb8-4621-a717-948394d6caac"
  },
  "resourceGroup": "MOCKUP",
  "sku": {
    "capacity": null,
    "family": null,
    "model": null,
    "name": "Premium_LRS",
    "size": null,
    "tier": "Premium"
  },
  "tags": null,
  "type": "Microsoft.Compute/disks"
}`

**Comment by kbute95** [comment] 2020-05-28 21:07
I'm experiencing this same issue when doing an image copy.  Any update on this?

**Comment by qwordy** [comment] 2020-06-17 08:03
I am not sure why it fails. Sometimes a HTTP request may fails and can succeed by retrying. Image copy does not have a retry mechanism. But according to the description in this PR, I don't think it's the cause.

**Comment by qwordy** [comment] 2020-06-17 08:07
> 
> 
> Unfortunately I get an error from that command:
> `Resource fragmdgpu_OsDisk_1_121312e46bb84621a717948394d6caac is not found.`
> But the disk does exist:
> ![image](https://user-images.githubusercontent.com/2699595/82864274-7e9bcc00-9f24-11ea-9c6e-b23cf811c3d0.png)

Could you add `--debug` to the command and run it again? I need logs to see where this error message come from.

**Comment by rispoli** [comment] 2020-06-17 12:17
Apologies @qwordy, I do not have access to that user Subscription anymore, hence it's not possible for me to retry with `--debug`. It was repeatable, though. The customer and I both tried several times and it never succeeded.
Hopefully @kbute95 or @cwiederspan can still replicate the issue and run with a higher verbosity level?

**Comment by raghus5040** [comment] 2020-08-20 15:14
even im facing the same issue 
I have tried with time out value too
"az image copy --source-resource-group My-resourcegroup  --source-object-name ABCNEW-image-20200820160045 --target-location southindia --target-resource-group "My-resourcegroup" --target-name ABCNEWdummy --timeout 3600000"

**Comment by qwordy** [comment] 2020-08-24 01:40
Can't reproduce yet. Close it for now. An IcM incident is opened to track it.

**Closed by qwordy** 2020-08-24 01:40 UTC
Labels: Compute, customer-response-expected, extension/image-copy
