### ISSUE TITLE
az artifacts universal download fails 

### ISSUE THREAD

**Issue by Pegolon** [Azure/azure-cli-extensions#554] opened 2019-03-05 16:58 UTC
I have installed az-cli on my macOS 10.14.3 system with:
$ brew update && brew install azure-cli
$ az extension add --name azure-devops
Then successfully logged in with 
$ az login
When I want to download a universal artifact from my Azure Devops account with:
$ az artifacts universal download --feed "XXX" --name "YYY" --path . --version "###" --org "https://dev.azure.com/zzzzzz/"

The binary is being downloaded, but then I get the following errors (reproducible on two different machines):
`
[GetBuildDropManagerAsync] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 2/5, retryable exception caught. Retrying in 00:00:02.0460000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 3/5, retryable exception caught. Retrying in 00:00:04.4350000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 4/5, retryable exception caught. Retrying in 00:00:07.7130000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 5/5, retryable exception caught. Retrying in 00:00:13.2850000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 6/5, retryable exception caught, but retries have been exhausted. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
Encountered an unexpected error.
Microsoft.VisualStudio.Services.Common.VssServiceException: TF400813: The user 'GUID\my-email-address' is not authorized to access this resource.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.CreateDataProviderAsync(String location, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at ArtifactTool.BuildDropManagerProvider.GetBuildDropManagerAsync(String serviceUrl, String patVar, ILogger commandBaseLogger, IAppTraceSource tracer, CancellationToken cancellationToken)
   at ArtifactTool.Commands.UPackDownloadCommand.ExecuteAsync()
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args)
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa27bc14-1989-60eb-06ea-1270d9fbf0f1
* Version Independent ID: 1f391f98-ac28-ba9f-366a-447c1f9e4feb
* Content: [az artifacts universal](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/artifacts/universal?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/artifacts/universal.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/artifacts/universal.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Pegolon** [comment] 2019-03-06 09:38
Just tested on Windows 10, same results.

**Comment by williexu** [comment] 2019-03-06 18:27
@gauravsaralMs could you take a look?

**Comment by gauravsaralMs** [comment] 2019-03-07 10:53
@mitchdenny @zarenner: can you please take a look?

**Comment by mitchdenny** [comment] 2019-03-12 12:28
ack. I've shared it with our DRI to look into. @Pegolon. Could you create a new feed and try uploading a package to it?

**Comment by Pegolon** [comment] 2019-03-12 12:42
Update azure-cli to 2.0.60, extension azure-devops still version 0.3.0, created new feed, created new artifact on feed from build pipeline, unfortunately the error messages stayed the same.

**Comment by mitchdenny** [comment] 2019-03-12 12:44
So the error you are getting is coming from a build pipeline? Or the pipeline succeeded to publish and you couldn't download. Is your Pipeline running on a hosted agent?

I'm suspecting an authn/authz issue here. Can you try doing an az login again?

**Comment by Pegolon** [comment] 2019-03-12 12:47
No, on Azure DevOps web interface I can create the artifact and **upload** it to the feed. It is listed there and looks ok. However with the command line tools I cannot **download** it. az login always succeeds. I am using the admin user which created the feed and manages the build pipelines, so permission should not be a problem.

**Comment by mitchdenny** [comment] 2019-03-12 15:33
When you say you create the artifact and upload it on the web-interface  what do you mean? The only way to upload Universal Packages is via the Azure CLI or via a Azure Pipelines.

**Comment by Pegolon** [comment] 2019-03-12 15:48
Sorry for being unprecise: of course the artifact is being created by the build pipeline. My main problem is that I cannot download it. Background: I am building a macOS framework and putting it in an artifact which I want to use in other projects. I thought the command line tools would let me download it directly, since I need it during development, but then later also when building the final app. So my main problem, as the subject of this issue states is with "download".

**Comment by fadnavistanmay** [comment] 2019-03-13 16:54
Hi @Pegolon , A quick question, in your build pipeline, which task are you using to upload - Universal packages or Publish Pipeline Artifact?? This will help us reproduce on our end.

P.S - I think the subject should not have "Mac OS" as the issue is reproducible on Windows as well.

Thanks,
Tanmay

**Comment by Pegolon** [comment] 2019-03-13 16:59
@fadnavistanmay I added "Mac OS" to the title since I discovered the problem there first. Removed it now from the subject.
This is my pipeline task for uploading the artifact:
- task: UniversalPackages@0
  displayName: Publish framework
  inputs:
    command: publish
    publishDirectory: '$(Build.BinariesDirectory)/Build/Products/Release/MyCustom.framework'
    vstsFeedPublish: 'MacOS'
    vstsFeedPackagePublish: 'macos.mycustom.framework'
    versionOption: custom
    versionPublish: '$(framework_version).$(Build.BuildId)'
    packagePublishDescription: 'Self-contained framework containing dotnet core runtime'

**Comment by fadnavistanmay** [comment] 2019-03-13 22:06
Thanks @Pegolon . I am trying to repro this. Is there a reason you are using az cli to download, to unblock can you try using the UniversalPackages Download task to download.?

Thanks,
Tanmay

**Comment by Pegolon** [comment] 2019-03-14 09:39
I want to use both: while developing I want to use the CLI to download the framework, when building on a pipeline during CI/CD I want to use the download task. That way I can reduce the complexity that CocoaPods brings to the table and I have a prebuilt binary framework available and don't need to check it into a separate repository.

**Comment by mitchdenny** [comment] 2019-03-14 16:38
@Pegolon I think we are going to need to transition to e-mail to exchange a few detailed logs so we can try and track this down. Can you e-mail me on midenn at microsoft.com and I'll get you connected directly to the engineers and we can talk about getting Fiddler traces etc.

**Comment by Pegolon** [comment] 2019-03-20 13:07
@mitchdenny I finally got it working. Set up a new project, migrated my source from the old project, built the framework and upload it successfully. After that "az artifacts universal download..." from the commandline did not complain anymore and it downloaded the package. Not really sure what is different now.

**Comment by 24mu13** [comment] 2019-04-11 10:07
I had same problem when uploading/downloading from old-organization-URL ... may be the problem is related to the old URL-style ...

**Comment by draiche** [comment] 2019-04-11 20:13
I'm having this problem as well. I'm on Windows 10 running the latest version of the azure-cli (2.0.62) and azure-devops (0.4.0).

`az artifacts universal download --feed "my-feed" --name "myartifact" --path "C:\Users\X\Desktop\" --version "1.0.0" --org "https://dev.azure.com/myname"`

I get the exact same error as Pegolon:

`Universal Packages is currently in preview.
[VerifyConnectionAsync] Try 1/2, retryable exception caught. Retrying in 00:00:01. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[VerifyConnectionAsync] Try 2/2, retryable exception caught. Retrying in 00:00:02.1070000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[VerifyConnectionAsync] Try 3/2, retryable exception caught, but retries have been exhausted. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
Encountered an unexpected error.
Microsoft.VisualStudio.Services.Common.VssServiceException: TF400813: The user 'my-guid\my-name@company.com' is not authorized to access this resource.
.....
.....`

I have tried creating an entirely new organization with an entirely new Artifacts feed, I've tried using both az login and az devops login with the same results. If I intentionally login to a different azure account which does not have access to the resource, I get a one-line sensible error that my user is not authorized to access this resource, but without the large exception dump.

Furthermore, using the VSTS CLI equivalent of this, which has *almost* the exact same parameters works great. I was able to upload and download universal files using the VSTS CLI, and have tried downloading those with az artifacts universal and uploading new files, but all with the same results.

**Comment by Welchen** [comment] 2019-05-03 02:20
I'm having this same issue. I was having a different issue of an access denied when trying to install the artifacttool but now I am having this issue.  Any suggestions? Trying to download.

**Comment by clowtown** [comment] 2019-05-14 13:40
Our main issue so far has been the already reported issue of artifacttool not using the proxy variables correctly. Be defined in various forms in windows environment, via network configuration, etc. With debug, we can see the transition from vsts cli to artifact tool hang making a secure request. Running from off network is not an option as security requires us to be on network in order to connect to vsts.

**Comment by fadnavistanmay** [comment] 2019-05-14 19:07
@geverghe - Could you please look into this. This feels like an issue with the credential store and how the az cli is accessing it?

Thanks

**Comment by geverghe** [comment] 2019-05-15 05:16
Looping in @gauravsaralMs to investigate.

**Comment by gauravsaralMs** [comment] 2019-05-15 06:02
@fadnavistanmay : can you please share the logs to point that this is an issue with credential store? and can you also share the repro steps for the same?

**Comment by bonettebueno** [comment] 2019-05-22 14:35
Hey guys ... same issue on Windows10



> Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called

Any idea for workaround?

**Comment by 24mu13** [comment] 2019-06-10 14:17
Great, it worked also for me:
```
az logout
az devops login
```

> I'm having this problem as well. I'm on Windows 10 running the latest version of the azure-cli (2.0.62) and azure-devops (0.4.0).
> 
> `az artifacts universal download --feed "my-feed" --name "myartifact" --path "C:\Users\X\Desktop\" --version "1.0.0" --org "https://dev.azure.com/myname"`
> 
> I get the exact same error as Pegolon:
> 
> `Universal Packages is currently in preview. [VerifyConnectionAsync] Try 1/2, retryable exception caught. Retrying in 00:00:01. Details: Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called? [VerifyConnectionAsync] Try 2/2, retryable exception caught. Retrying in 00:00:02.1070000. Details: Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called? [VerifyConnectionAsync] Try 3/2, retryable exception caught, but retries have been exhausted. Details: Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called? Encountered an unexpected error. Microsoft.VisualStudio.Services.Common.VssServiceException: TF400813: The user 'my-guid\my-name@company.com' is not authorized to access this resource. ..... .....`
> 
> I have tried creating an entirely new organization with an entirely new Artifacts feed, I've tried using both az login and az devops login with the same results. If I intentionally login to a different azure account which does not have access to the resource, I get a one-line sensible error that my user is not authorized to access this resource, but without the large exception dump.
> 
> Furthermore, using the VSTS CLI equivalent of this, which has _almost_ the exact same parameters works great. I was able to upload and download universal files using the VSTS CLI, and have tried downloading those with az artifacts universal and uploading new files, but all with the same results.
> 
> **UPDATE:** I was able to eventually get around this by using removing az devops login and instead having it retrieve my PAT from an environment variable.

**Comment by geverghe** [comment] 2019-06-12 06:28
@elbatk for visibility into the issue and take the appropriate action here.

**Comment by fadnavistanmay** [comment] 2019-06-25 23:09
@owenhuynmsft

**Comment by JoseSBarrientos** [comment] 2019-09-26 14:01
I had the same problem and it turned out to be a network issue. In my case, at least one artifact had to exist inside the folder C:\Users\x\.azure\azuredevops\cli\tools\artifacttool\name_of_artifact\ to be able to download the files. Not sure if this is your case but you it is worth trying in case you have not resolved it yet.

**Comment by atbagga** [comment] 2019-11-19 08:13
Closing this issue in favor of tracking it in the azure-devops extension repo. 
Please see https://github.com/Azure/azure-devops-cli-extension/issues/833 for further updates and discussions.

**Closed by atbagga** 2019-11-19 08:13 UTC
Labels: extension/devops
