### ISSUE TITLE
Improve handling of SSH fingerprints

### ISSUE THREAD

**Issue by tap1992** [Azure/azure-cli-extensions#4492] opened 2022-03-04 12:58 UTC
### Extension name (the extension in question)
SSH

### Description of issue (in as much detail as possible)
If a Azure Virtual Machine is rebuilt (after having already used Az SSH VM to connect to it and accept the fingerprint) and then try and connect to it again, the AZ CLI won't do anything, doesn't present any errors just returns to the command prompt.

Putty (using local username and password) can still connect to the VM perfectly fine in this scenario.

If I delete the C:\Users\<user>\.ssh folder and then try reconnecting to the same Azure VM it will ask me to accept the fingerprint and it then connects fine.
-----

**Comment by yonzhan** [comment] 2022-03-04 13:59
route to CXP team

**Comment by navba-MSFT** [comment] 2022-05-05 07:15
@tap1992 Apologies for the late reply. Thanks for reporting this issue and sharing this feedback. 

>_If a Azure Virtual Machine is rebuilt (after having already used Az SSH VM to connect to it and accept the fingerprint) and then try and connect to it again, the AZ CLI won't do anything, doesn't present any errors just returns to the command prompt._

Action Plan: You could try to run the command with verbosity flag as shown below to know what request / operation is being performed. So looking at the output returned you can take a guess on if the command did succeed or fail. 

>az ssh vm -n <machine-name> -g <resource-group> -- -v

The ssh issue post VM rebuild has been raised before and its being worked upon by the Service team. Refer # Azure/azure-cli#21038. So this issue would be a duplicate of that.

Until the fix is released the only workaround would be to delete the contents of` %userprofile%\.ssh\known_hosts `
Hope this helps.

**Closed by navba-MSFT** 2022-05-05 07:15 UTC
Labels: customer-reported, VM SSH, CXP Attention, Auto-Assign
