### ISSUE TITLE
az ssh extension no longer displaying SSH banner correctly as of v1.1.1

### ISSUE THREAD

**Issue by eehret** [Azure/azure-cli-extensions#4915] opened 2022-05-31 13:17 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
az ssh

### Extension name (the extension in question)
ssh

### Description of issue (in as much detail as possible)

In previous versions of az ssh extension, the SSH login banner was correctly displayed *while* the user logs in, and it is one of the first things they see.
Now, since updating my az ssh extension, the banner no longer appears when it should, instead appearing after the user *logs out*, which means the banner can no longer serve its purpose. 
In our corporate environment the SSH banner serves as an important element of our security posture, advising users on what expectations they should or should not have while logged into the system.  For example, they would be advised not to expect their actions to be private, since all actions are logged.

Please fix this so the banner appears before/during login instead of after logout.

-----

**Comment by yonzhan** [comment] 2022-05-31 14:27
route to CXP team

**Comment by SatishBoddu-MSFT** [comment] 2022-06-06 16:57
@eehret   Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment] 2022-06-07 22:08
Hello @eehret thanks for reporting this issue, we are routing this to the Service team's attention for further action.

**Comment by vthiebaut10** [comment] 2022-07-05 17:34
@eehret Thanks for reporting this problem. I need a little bit more detail to address this issue. Would it be possible to share a screenshot (with sensitive information redacted) of the expected and current behaviors?

**Comment by eehret** [comment] 2022-07-27 16:00
@vthiebaut10  Sure, no problem.

![ad_ssh_correct_behaviour](https://user-images.githubusercontent.com/1770106/181294115-b26ce10c-7168-4460-9397-1941691bef87.jpg)

![ad_ssh_incorrect_behaviour](https://user-images.githubusercontent.com/1770106/181294147-f9afdc11-938a-4a36-a5a2-406071bf8ecc.jpg)

As you can see, with the correct behaviour the banner is the very first thing that the user sees while logging in, whereas with the incorrect behaviour the banner is not shown until they terminate their session, rendering it completely useless from a legal perspective.

**Comment by vthiebaut10** [comment] 2022-07-27 18:07
@eehret Thank you for sharing more details on the issue. I've identified the cause of the problem, and I'll schedule time to work on a solution. I'll update this issue once we release a fix.

**Comment by eehret** [comment] 2022-08-02 14:02
@vthiebaut10 That's great, thanks for letting me know!

**Comment by eehret** [comment] 2022-09-12 15:22
@vthiebaut10 Hi there,
I was wondering if there is any update on this?  It has been a problem for quite a while now.

**Comment by vthiebaut10** [comment] 2022-09-12 15:24
Hi @eehret - sorry for the long delay. We are planning to release an update soon, and that will include a fix for this. Thank you for your patience, and sorry for the long wait.

**Closed** 2022-10-21 02:42 UTC
Labels: customer-reported, Service Attention, VM SSH, Auto-Assign

**Comment by eehret** [comment] 2022-10-28 20:31
@vthiebaut10 Thanks for taking care of this.   I can confirm that as of the latest version of the az ssh module (1.1.3) this is now working as expected.
