### ISSUE TITLE
Unexpected error "syntax is incorrect"

### ISSUE THREAD

**Issue by kostyar007** [Azure/azure-cli-extensions#4483] opened 2022-03-02 21:47 UTC
## Describe the bug

**Command Name**
`az ssh config
Extension Name: ssh. Version: 1.0.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\krazumov\\Documents\\az_ssh_config\\*'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\krazumov\.azure\cliextensions\ssh\azext_ssh\custom.py", line 53, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip,
  File "C:\Users\krazumov\.azure\cliextensions\ssh\azext_ssh\custom.py", line 90, in _do_ssh_op
    public_key_file, private_key_file, delete_keys = _check_or_create_public_private_files(public_key_file,
  File "C:\Users\krazumov\.azure\cliextensions\ssh\azext_ssh\custom.py", line 189, in _check_or_create_public_private_files
    os.makedirs(credentials_folder)
  File "os.py", line 223, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\krazumov\\Documents\\az_ssh_config\\*'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --ip {} --file {} --overwrite`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.0

Extensions:
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by kostyar007** [comment] 2022-03-02 21:53
I used the command from PowerShell:
az ssh config --ip * --file C:\Users\krazumov\Documents\azurevm.txt --overwrite
The path 'C:\\Users\\krazumov\\Documents\\az_ssh_config\\*' exists but somehow doesn't excepted.

**Comment by yonzhan** [comment] 2022-03-02 22:54
route to CXP team

**Comment by navba-MSFT** [comment] 2022-03-03 03:19
@kostyar007 Thanks for reaching out to us. Could you please follow the below action plan in the order and let me know if that works ?

>az ssh config --ip 23.XXX.XX.86 --file ./sshconfig # Add the right public IP address of the VM
ssh -F ./sshconfig 23.XXX.XX.86

**Note**: You need to pass relative path to the `--file` parameter and not absolute path. 

PS: Even if the error/warning appears while running the above command it should succeed in the background. The sshconfig file should be created. Please let me know if you face any issues. Awaiting your reply.

**Comment by kostyar007** [comment] 2022-03-03 18:25
@navba-MSFT ,
The command works when I use IP address explicitly. It doesn't work when I use asterisk.
az ssh config --ip * --file Documents\azurevm2.txt --overwrite

**Comment by navba-MSFT** [comment] 2022-03-04 04:22
@kostyar007 Thanks for getting back. The way your run the command depends on the command shell you are using. Sending you the syntax for using asterisk.

#Bash
az ssh config --ip \* --file ./sshconfig

#PowerShell
az ssh config --ip * --file ./sshconfig

Hope this helps.

**Comment by kostyar007** [comment] 2022-03-04 18:22
@navba-MSFT, thanks for quick response.
It doesn't help for PowerShell:
PS C:\Users\krazumov> az ssh config --ip * --file ./sshconfig
The command failed with an unexpected error. Here is the traceback:
[WinError 123] The filename, directory name, or volume label syntax is incorrect: '.\\az_ssh_config\\*'

**Comment by navba-MSFT** [comment] 2022-03-08 03:57
@kostyar007 Thanks for getting back. I was able to reproduce the issue at my end. Turns out that it is a bug and we will have that fixed on the next version of the extension. So I have tagged this github issue with Bug label.

For now, you can use the `--keys-destination-folder` parameter to avoid the error when creating config files with * as the IP. The error happens because the extension tries to create a folder for the keys with the provided IP in the name and that is not possible.

Example:
> az ssh config --file ./sshconfig --ip * --keys-destination-folder C:\users\<username>\my_keys

You might get a warning about the security while running this command. But your config file should be created. Let me know if that solves your problem, and thank you for bringing this bug to our attention.

**Comment by kostyar007** [comment] 2022-03-08 19:25
@navba-MSFT Thank you. It works.

**Comment by navba-MSFT** [comment] 2022-03-09 04:02
@kostyar007 Thanks for getting back. I am glad that the issue is resolved. We will update this thread once the above issue is fixed in next version of extension. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed** 2022-03-09 04:03 UTC
Labels: bug, customer-reported, VM SSH, CXP Attention, Auto Assign
