### ISSUE TITLE
az network bastion rdp does not work for IP-based connection

### ISSUE THREAD

**Issue by Sahil-13** [Azure/azure-cli-extensions#6032] opened 2023-03-17 17:00 UTC
## Describe the bug
Since last few days , we are experiencing issues with RDP connection to Azure VMs using `az network bastion rdp` **IP-Based** command. Few of our observations below - 
- the operation fails in few regions, so far we have tested Canadeast , Canada Central and West Europe. 
- the command/operation works fine using `--target-resource-id` parameter irrespective of the region
- IP based connection using "Connect" option  from the Bastion blade in the portal works fine.

**Command Name**
`az network bastion rdp
Extension Name: bastion. Version: 0.2.3.`

**Errors:**
```
While the command does not display any error but I occasionally I get "An Internal Error Occured" dialogue box once the requested RDP connection fails or sometimes the "Remote Desktop Connection" keeps connecting without any error, post cancellation we get 
**[WinError 10054] An existing connection was forcibly closed by the remote host** only when we run the command with `--debug` flag.


```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Bastion resource should be deployed in Canada East region

- `az network bastion rdp --name {} --resource-group {} --target-ip-address {} ` 
or
- `az network bastion rdp --name {} --resource-group {} --target-ip-address {} --debug`

## Expected Behavior

Upon successful completion of the command and remote desktop connection, we should get login prompt to enter our username and password for the VM to login. 

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
account 0.2.1
bastion 0.2.3
interactive 0.4.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
if this helps
msal.telemetry: Generate or reuse correlation_id: b6398262-da94-419a-8a72-196b25642623

**Comment by juanantonioforner** [comment] 2023-03-17 17:07
Same here, I am also experiencing this issue with az network bastion rdp on IP-based connections in Canada East region, it was working fine a few days ago, now it always fails.

**Comment by yonzhan** [comment] 2023-03-17 23:03
route to CXP team

**Comment by Sahil-13** [comment] 2023-03-20 15:04
I am writing this to share an update post further testing, it was found that other regions are also impacted for example - Canada Central, West Europe and of course Canada East. I have made the correction in my main issue description.

**Comment by aavalang** [comment] 2023-03-22 17:21
@yonzhan assign this to me, we are working to fix this.

**Comment by IT-Daniel** [comment] 2023-03-23 14:30
Hello everyone,

Any news on this topic?

**Comment by IT-Daniel** [comment] 2023-03-24 10:19
@Sahil-13 I opened a support ticket with Azure support team and they confirmed me that this feature was unintentionally released, so they rolled it back so they can test it and put in general availability in the future. It seems that, at the moment, we won't be able to use it to connect through IP...

**Comment by onozaty** [comment] 2023-03-24 13:01
This feature is also available as documentation, so many people may be using it.
I use it myself.

I hope it will be officially released soon🙏.

**Comment by mbeaudin** [comment] 2023-03-31 23:00
Any update here? We have also been affected by this issue for several weeks and have an outstanding ticket with Azure Support as well.

**Comment by AussieDavo** [comment] 2023-04-01 10:41
We also seem to be experiencing this issue in Australia East. Any updates?

**Comment by IT-Daniel** [comment] 2023-04-03 09:27
Hi @mbeaudin @AussieDavo this feature will not be available soon. I've been told that it's still on development and there is no concrete deployment date, so don't expect to use the '--target-ip-address' argument at the moment. The connection via '--target-resource-id' works though.

**Comment by AussieDavo** [comment] 2023-04-09 22:33
Hi @IT-Daniel ,
I'm using the "az network bastion tunnel" command as documented here: [az network bastion tunnel](https://learn.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#az-network-bastion-tunnel)
I'm attempting to use the "--target-ip-address" switch however I am unable to connect using either RDP or SSH. The tunnel connection is established successfully within Azure CLI, but I am unable to connect successfully to localhost on the specified local port using Putty or the Remote Desktop Connection app (mstsc.exe).
Attempted Command:
`az network bastion tunnel --name MyBastionHost --resource-group MyResourceGroup --target-ip-address 10.0.0.1 --resource-port 22 --port 50022`
I can however connect to the same IP address successfully using the Connect blade on the Bastion resource within the Azure Portal.
You are right, a connection using the '--target-resource-id' works for Azure resources, however connecting to IP's outside of Azure using the "IP-based connection" feature is not possible. IP-based connection documentation here, showing connectivity to hosts outside of Azure: [Connect to a VM via specified private IP address through the portal](https://learn.microsoft.com/en-gb/azure/bastion/connect-ip-address)
Not sure if this is by design, as it does specifically state "through the portal" in the documentation.
@aavalang - is this something that can be resolved in the Azure CLI bastion extension?
Having "Native client support" and "IP-based connection" working together would be hugely advantageous.

**Comment by juanantonioforner** [comment] 2023-04-13 07:40
Same here, it is working fine, I will ask Microsoft support to get confirmation about issue is permanently solved or they are still troubleshooting issue.

**Comment by aavalang** [comment] 2023-04-13 15:55
@yonzhan can you close this issue

**Closed** 2023-04-13 23:09 UTC
Labels: bug, customer-reported, Network, Service Attention, Client, Network - Bastion, Auto-Assign
