### ISSUE TITLE
aks-preview extension breaks --enable-defender parameter for aks command module

### ISSUE THREAD

**Issue by sdolgin** [Azure/azure-cli-extensions#4921] opened 2022-06-01 14:17 UTC
### Related command
az aks update --resource-group myGroup --name myCluster --enable-defender

### Extension name (the extension in question)
aks-preview

### Description of issue (in as much detail as possible)
When trying to run the following with the aks-preview extension (0.5.76):
```
az aks update --resource-group myGroup --name myCluster --enable-defender
```
The output returns an error: `unrecognized arguments: --enable-defender`

When I remove the aks-preview extension the command runs successfully.  I am able to reproduce this issue in Cloud Shell.  Here is the output of az version:
```
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.5.76",
    "ssh": "1.1.1"
  }
}
```

**Comment by FumingZhang** [comment] 2022-06-14 01:37
Hi @sdolgin, sorry for the inconvenience. The defender related options are not supported in aks-preview yet. We will add support for it as soon as possible, expected within this week.

As for the workaround, please use this feature via the official CLI.

**Comment by RakeshMohanMSFT** [comment] 2022-06-14 02:48
@sdolgin Since you already confirmed that the work around is working for you. I will go ahead and close this issue.

**Closed by RakeshMohanMSFT** 2022-06-14 02:48 UTC
Labels: AKS, needs-author-feedback, CXP Attention, Auto-Assign
