### ISSUE TITLE
Submitting AML pipeline from CLI yields error

### ISSUE THREAD

**Issue by joe-plumb** [Azure/azure-cli-extensions#1744] opened 2020-05-20 11:26 UTC
## Describe the bug

**Command Name**
`az ml run submit-pipeline
Extension Name: azure-cli-ml. Version: 1.3.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


I/O operation on closed file
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 220, in invoke
    formatter = self.output.get_formatter(output_type)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 165, in get_formatter
    if not sys.stdout.isatty() and format_type == 'jsonc':
ValueError: I/O operation on closed file
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ml run submit-pipeline -n {} -y {} -w {} -g {} -o {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *
azure-cli-ml 1.3.0

Extensions:
azure-cli-ml 1.3.0

```

**Comment by yonzhan** [comment] 2020-05-20 12:03
ml

**Comment by tiagoh** [comment] 2020-05-25 07:46
any updates on this bug ? I have come across it also recently with SDK 1.5.0

**Comment by ignaciofls** [comment] 2020-05-25 10:56
Hi @joe-plumb and @yonzhan , 

I found a workaround, the issue is definitely with the azure-cli version. I went to my history of executed pipelines and found that the last environment that worked well was azure-cli 2.2.0 and ml extension 1.2 so I tried to downgrade the azure-cli with no luck (i believe there is no such option). Using bash tasks is fairly straightforward to install anything in your ubuntu agent, so download the deb package, remove the new one and install the 2.2.0 version as follows:

steps:
- task: Bash@3
  displayName: 'Download 2.2.0 CLI'
  inputs:
    targetType: 'inline'
    script: 'sudo curl https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.2.0-1~xenial_all.deb --output cli.deb'

- task: AzureCLI@1
  displayName: 'Uninstall CLI'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'sudo apt-get remove -y azure-cli'

- task: Bash@3
  displayName: 'Install 2.2.0 CLI'
  inputs:
    targetType: 'inline'
    script: 'sudo apt install ./cli.deb'

- task: AzureCLI@1
  displayName: 'Install the ML CLI extension'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.2.0-py2.py3-none-any.whl --yes -y'

Once pipelined it works well, enjoy it!

**Comment by joe-plumb** [comment] 2020-05-27 10:09
Thanks @ignaciofls , this workaround worked for me.

**Comment by j-so** [comment] 2020-05-28 18:16
We have identified the issue and are working on a fix.

In the meantime:

Switching to an older version as @ignaciofls suggested is a workaround.

If you're using this as part of a AzureDevOps Pipeline:
1. If you are able to ignore stderr (i.e. [ADO bash task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) - failOnStderr: false), you can still use this command to submit pipelines. To get the output, you can specify a file to write the output json to using the "-f" parameter.
1. You can try using the [AzureML Published Pipeline](https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.vss-services-azureml) for agentless job. This should not be affected by this issue.

**Comment by j-so** [comment] 2020-06-03 00:07
We have released an [SDK patch](https://pypi.org/project/azureml-core/) to fix this issue. i.e. `pip install --upgrade azureml-core`

The `az ml submit-pipeline` command should now output correctly.

**Comment by lilyjma** [comment] 2020-06-16 07:04
Closing this issue as it appears to be resolved. Please feel free to open a new issue if needed.

**Closed by lilyjma** 2020-06-16 07:04 UTC
Labels: Service Attention, extension/ml, question
