### ISSUE TITLE
az ssh fails az cli 2.46.0 + ssh extention 1.1.4, but success with 1.1.3

### ISSUE THREAD

**Issue by jrmanisme** [Azure/azure-cli-extensions#5986] opened 2023-03-14 13:12 UTC
### **This is autogenerated. Please review and update as needed.**

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## Describe the bug

**Command Name**
`az ssh vm
Extension Name: ssh. Version: 1.1.4.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
ssh 1.1.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context

az ssh vm --name MYVM--resource-group MYRG
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\myuser\.azure\cliextensions\ssh\azext_ssh\custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "C:\Users\myuser\.azure\cliextensions\ssh\azext_ssh\custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "C:\Users\myuser\.azure\cliextensions\ssh\azext_ssh\ip_utils.py", line 36, in get_ssh_ip
    if public_ip_ref and public_ip_ref.get("id", None):
AttributeError: 'str' object has no attribute 'get'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by jrmanisme** [comment] 2023-03-14 14:42
You probably introduced a python bug into 1.1.4
Installing az 2.35.0 is installing ssh extention 1.1.3 then I can make az ssh vm
az upgrade is installing today latest az which is 2.46.0 but not upgrading ssh extention, fortunatelly !!!
then az ssh vm works properly with 2.46.0 + 1.1.3 ssh extention

**Comment by yonzhan** [comment] 2023-03-14 23:21
route to CXP team

**Comment by navba-MSFT** [comment] 2023-03-15 04:30
@jrmanisme Duplicate of https://github.com/Azure/azure-cli-extensions/issues/5984  

Please track the progress of this issue here https://github.com/Azure/azure-cli-extensions/issues/5984

**Closed by navba-MSFT** 2023-03-15 04:30 UTC
Labels: question, customer-reported, VM SSH, CXP Attention, Auto-Assign
