### ISSUE TITLE
az network bastion tunnel fails

### ISSUE THREAD

**Issue by bvoogel** [Azure/azure-cli-extensions#5859] opened 2023-02-07 21:26 UTC
## Describe the bug

**Command Name**
`az network bastion tunnel
Extension Name: bastion. Version: 0.2.0.`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion tunnel --name {} --resource-group {} --target-resource-id {} --resource-port {} --port {}`

## Environment Summary
```
macOS-13.2-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
bastion 0.2.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by bvoogel** [comment] 2023-02-07 21:28
Command group 'az network' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
_validate_and_generate_resourceid() missing 1 required positional argument: 'target_ip_address'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/bradleyvoogel/.azure/cliextensions/bastion/azext_bastion/custom.py", line 349, in create_bastion_tunnel
    _validate_and_generate_resourceid(cmd, bastion, target_resource_id, target_ip_address)
TypeError: _validate_and_generate_resourceid() missing 1 required positional argument: 'target_ip_address'

**Comment by yonzhan** [comment] 2023-02-08 00:07
route to CXP team

**Comment by navba-MSFT** [comment] 2023-02-08 05:07
@bvoogel Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by aavalang** [comment] 2023-02-08 18:25
fixing this issue in 0.2.1

**Comment by navba-MSFT** [comment] 2023-02-09 05:47
Thanks for the update @aavalang

**Comment by jcaton-msft** [comment] 2023-02-17 17:56
I hit this issue last week as well.  I've confirmed its fixed in bastion 0.2.1 version.

**Comment by aavalang** [comment] 2023-05-18 18:59
can you run an upgrade on the az bastion extension, that should potentially fix this issue

**Comment by AkechiShiro** [comment] 2023-07-25 09:45
If this issue is fixed it should be closed.

**Comment by aavalang** [comment] 2023-11-27 18:00
@yonzhan can you please close this

**Comment by AkechiShiro** [comment] 2023-11-27 18:31
Do you confirm the issue is fixed @aavalang?

**Closed** 2023-11-27 23:01 UTC
Labels: bug, customer-reported, Network, Service Attention, Network - Bastion, Auto-Assign

**Comment by rgunczer** [comment] 2024-01-23 23:50
I'm getting this issue again with:
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "bastion",
    "path": "/home/flan/.azure/cliextensions/bastion",
    "preview": false,
    "version": "0.3.0"
  }
]
