### ISSUE TITLE
Typo in the Examples Section

### ISSUE THREAD

**Issue by phillipsj** [Azure/azure-cli-extensions#549] opened 2019-03-01 15:56 UTC
The spacing is incorrect between the two commands. in the example section. I would submit a PR to correct, but I don't see the option on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc0dc836-b360-332c-dc75-c00775148a77
* Version Independent ID: a687237c-d250-298c-e583-3ee07106e600
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/ext/webapp/webapp?view=azure-cli-latest#examples)
* Content Source: [latest/docs-ref-autogen/ext/webapp/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/webapp/webapp.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment] 2019-03-01 16:19
@phillipsj which command has the erroneous example?  @adewaleo do you know why the edit button doesn't appear here?

**Comment by phillipsj** [comment] 2019-03-01 16:57
This section, the command isn't incorrect, but you have all that white space.
![image](https://user-images.githubusercontent.com/1568133/53653355-1ffc7b00-3c19-11e9-9e45-8ad2335b440b.png)

**Comment by williexu** [comment] 2019-03-01 18:11
@phillipsj the problem is here: https://github.com/Azure/azure-cli-extensions/blob/master/src/webapp/azext_webapp/_help.py#L16

@dendeli-msft would you have more information on the extension docs editing button?

**Comment by panchagnula** [comment] 2019-06-25 00:01
closing this since this command has been moved to core . If this is still an issue please re-open in the azure-cli repo. Thanks!

**Closed by panchagnula** 2019-06-25 00:01 UTC
Labels: extension/webapp
