### ISSUE TITLE
az ssh config -- AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by mdean-msm** [Azure/azure-cli-extensions#3586] opened 2021-07-06 00:58 UTC
## Describe the bug

**Command Name**
`az ssh config
Extension Name: ssh. Version: 0.1.5.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/mdean/.azure/cliextensions/ssh/azext_ssh/custom.py", line 28, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip, op_call)
  File "/home/mdean/.azure/cliextensions/ssh/azext_ssh/custom.py", line 40, in _do_ssh_op
    ssh_ip = ssh_ip or ip_utils.get_ssh_ip(cmd, resource_group, vm_name, use_private_ip)
  File "/home/mdean/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 27, in get_ssh_ip
    parsed_ip_id = tools.parse_resource_id(public_ip_ref.id)
AttributeError: 'NoneType' object has no attribute 'id'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --resource-group {} --name {} --file {}`

## Environment Summary
```
Linux-5.11.21-100.fc32.x86_64-x86_64-with-glibc2.2.5
Python 3.8.10
Installer: RPM

azure-cli 2.25.0

Extensions:
ssh 0.1.5

```

**Comment by yonzhan** [comment] 2021-07-06 02:18
SSH

**Comment by Juliehzl** [comment] 2021-07-13 03:02
dupe of https://github.com/Azure/azure-cli-extensions/issues/3501

**Closed** 2021-07-13 03:08 UTC
Labels: VM SSH
