### ISSUE TITLE
az image copy from image gallery in a different region fails

### ISSUE THREAD

**Issue by WillLennon** [Azure/azure-cli-extensions#1619] opened 2020-04-28 22:51 UTC
## Describe the bug

I'm trying to copy an image from a private image gallery to a different region. The gallery is in Central US and my resource group is in East US 2.

**Command Name**
`az image copy
Extension Name: image-copy-extension. Version: 0.2.4.`

**Errors:**
```
Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'image', 'show', '--name', 'WindowsServer2016', '--resource-group', 'gallery rg', '--output', 'json']' returned non-zero exit status 3.
Traceback (most recent call last):
pip-install-9101vebg\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 608, in execute
cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
az image copy --source-resource-group galleryRG --source-object-name WindowsServer2016 --target-location eastus2 --target-resource-group myRG

## Expected Behavior
Works or gives me an actionable error message.

## Actual Behavior:
command failed: ['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'image', 'show', '--name', 'WindowsServer2016', '--resource-group', 'sourceRG', '--output', 'json']
output: ERROR: Resource group 'sourceRG' could not be found.

The command failed with an unexpected error. Here is the traceback:

Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'image', 'show', '--name', 'WindowsServer2016', '--resource-group', 'mmsimagebuild', '--output', 'json']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-9101vebg\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\wlennon\.azure\cliextensions\image-copy-extension\azext_imagecopy\custom.py", line 31, in imagecopy
    json_cmd_output = run_cli_command(cli_cmd, return_as_json=True)
  File "C:\Users\wlennon\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 45, in run_cli_command
    raise ex
  File "C:\Users\wlennon\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'image', 'show', '--name', 'WindowsServer2016', '--resource-group', 'mmsimagebuild', '--output', 'json']' returned non-zero exit status 3.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0 *

Extensions:
image-copy-extension 0.2.4

```

**Comment by yungezz** [comment] 2020-04-29 00:54
hi @qwordy could  you pls have a look? thanks

**Comment by qwordy** [comment] 2020-05-10 06:04
Can you check whether the source resource group exist? The output said "ERROR: Resource group 'sourceRG' could not be found."
I test image copy command. I can run successfully.
```
az image copy --source-resource-group fytest3  --source-object-name image --target-resource-group fytest4 --target-location eastasia
Getting os disk id of the source vm/image
Creating source snapshot
Getting sas url for the source snapshot with timeout: 3600 seconds
Creating resource group: image-copy-rg
Target location count: 1
eastasia - Creating target storage account (can be slow sometimes)
eastasia - Creating container in the target storage account
eastasia - Copying blob to target storage account
eastasia - Copy progress: 0%
eastasia - Copy progress: 1%
eastasia - Copy progress: 2%
eastasia - Copy progress: 3%
eastasia - Copy progress: 4%
eastasia - Copy progress: 100%
eastasia - Copy time: 0:04:06.291520
eastasia - Creating snapshot in target region from the copied blob
eastasia - Creating final image
```

**Comment by qwordy** [comment] 2020-05-10 06:10
We have talked with more details in Teams.

**Comment by WillLennon** [comment] 2020-05-15 13:48
I asked for read access to the image gallery resource group and tried again.  It's still failing for me.

ERROR: The Resource 'Microsoft.Compute/images/WindowsServer2016' under resource group '<resourcegroup>' was not found.

**Comment by qwordy** [comment] 2020-05-19 02:55
Can you run `az image show --name WindowsServer2016 --resource-group mmsimagebuild --output json` successfully?

**Comment by qwordy** [comment] 2020-06-12 05:40
@WillLennon Could you try this command?

**Comment by qwordy** [comment] 2020-07-27 07:10
I cannot reproduce this issue and have not found cause based on the description. Close it now. Please open a new one if there is any issue.

**Closed** 2020-07-27 07:40 UTC
Labels: Compute, customer-reported, extension/image-copy
