### ISSUE TITLE
Generic Update has problem

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-cli-extensions#1917] opened 2020-06-22 06:07 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
datafactory see https://github.com/Azure/azure-cli-extensions/pull/1321

### Description of issue (in as much detail as possible)
1. if the generic_update_setter name is properties . it will become properties.properties in the request body

To repro: 
    `az datafactory linked-service update --ids "/subscriptions/92f95d8f-3c67-4124-91c7-8cf07cdbf241/resourceGroups/qiaozhatest/providers/Microsoft.DataFactory/factories/testfactoryforazregression/linkedservices/testlinkedservice" --set properties.description="test description" --debug `

2. if the  generic_update_setter name is pipeline. it will update the property I set but set the other part as null at the same time. Which is not expected.
Before:
![image](https://user-images.githubusercontent.com/55688292/85253796-843bf180-b491-11ea-9ea0-450fb9fe5934.png)
After I run the update command 
`az datafactory pipeline update --ids "/subscriptions/92f95d8f-3c67-4124-91c7-8cf07cdbf241/resourceGroups/qiaozhatest/providers/Microsoft.DataFactory/factories/regfactory/pipelines/myPipeline" --description "test pipeline"`
It becomes 
![image](https://user-images.githubusercontent.com/55688292/85253898-ae8daf00-b491-11ea-8953-83233a2f4a6f.png)
the activities become null.
 

-----

**Comment by yonzhan** [comment] 2020-06-22 06:13
Generic Update

**Comment by qiaozha** [comment] 2020-06-23 06:20
I have hidden the not working update now so that DF onboard will not be blocked by this. Please ping me when you start to work on this。 @jsntcy

**Comment by jsntcy** [comment] 2020-07-29 08:25
Offline synced with @qiaozha,

The root cause of the issue is because the type of response from Get() is different from the type of "properities" for Create_Or_Update(). One solution for this issue is that we should return instance.Properities instead of instance from method datafactory_linked_service_update(). Another solution is making the type of "properities" for Create_Or_Update() the same as the type of response from Get() (not flattern)

So close this issue.

**Closed by jsntcy** 2020-07-29 08:25 UTC
Labels: Generic Update, OKR3.2 Candidate
