### ISSUE TITLE
aks-preview fails with last release - cannot import name 'dis'

### ISSUE THREAD

**Issue by howardjones** [Azure/azure-cli-extensions#5303] opened 2022-09-02 10:15 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command

az aks get-credentials

### Extension name (the extension in question)

aks-preview

### Description of issue (in as much detail as possible)

The most recent release of aks-preview (0.5.96, 3 hours ago) fails to run `az aks get-credentials` with the following

```
    "stderr_lines": [
        "ERROR: The command failed with an unexpected error. Here is the traceback:",
        "ERROR: cannot import name 'dis'",
        "Traceback (most recent call last):",
        "  File \"/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py\", line 231, in invoke",
        "    cmd_result = self.invocation.execute(args)",
        "  File \"/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 561, in execute",
        "    self.commands_loader.load_arguments(command)",
        "  File \"/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py\", line 516, in load_arguments",
        "    loader.load_arguments(command)  # this adds entries to the argument registries",
        "  File \"/home/runner/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py\", line 47, in load_arguments",
        "    from azext_aks_preview._params import load_arguments",
        "  File \"/home/runner/.azure/cliextensions/aks-preview/azext_aks_preview/_params.py\", line 75, in <module>",
        "    from azext_aks_preview._validators import (",
        "  File \"/home/runner/.azure/cliextensions/aks-preview/azext_aks_preview/_validators.py\", line 13, in <module>",
        "    from sre_compile import dis",
        "ImportError: cannot import name 'dis'",
        "To open an issue, please run: 'az feedback'"
    ],
```

(output from ansible playbook)

-----

**Comment by howardjones** [comment] 2022-09-02 10:18
import in question was part of this PR:
https://github.com/Azure/azure-cli-extensions/pull/5295

**Comment by yonzhan** [comment] 2022-09-02 11:43
route to CXP team

**Comment by navba-MSFT** [comment] 2022-09-05 02:51
@howardjones Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-09-05 05:24
@howardjones You are using 0.5.96 version of the extension. Could you please update your` aks-preview` extension to the most recent version (**0.5.97**) and test again ?

>az extension update -n aks-preview

Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-09-07 07:51
@howardjones I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are still facing the same isue. Awaiting your reply.

**Comment by nikolaypopov** [comment] 2022-09-07 21:46
I am having exact same issue
`[root@df3c3c6af7d7 spawn]# az aks create
The command failed with an unexpected error. Here is the traceback:
cannot import name 'dis'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 47, in load_arguments
    from azext_aks_preview._params import load_arguments
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/_params.py", line 75, in <module>
    from azext_aks_preview._validators import (
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/_validators.py", line 13, in <module>
    from sre_compile import dis
ImportError: cannot import name 'dis'
To open an issue, please run: 'az feedback'`
No updates are available
`[root@df3c3c6af7d7 spawn]# az extension update -n aks-preview
No updates available for 'aks-preview'. Use --debug for more information.`
Using this extention
`[root@df3c3c6af7d7 spawn]# az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "aks-preview",
    "path": "/root/.azure/cliextensions/aks-preview",
    "preview": true,
    "version": "0.5.98"
  }
]`

**Comment by navba-MSFT** [comment] 2022-09-08 04:13
@howardjones I am unable to reproduce this issue.

```
$ az version
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    **"aks-preview": "0.5.98"**
   }
   }
```
   
$  az aks get-credentials -n MyAKS -g MyAKS
>Merged "MyAKS" as current context in /home/*******/.kube/config

I was able to run the AzCLI AKS command with 0.5.98 version of `aks-preview `extension. May I know the Azure CLI version you are using ? Could you please update you AzCLI to the[ most recent version](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli) (2.40.0) and check if that helps ?

**Comment by nikolaypopov** [comment] 2022-09-08 21:07
It looks like I am using 2.38.0
`
[root@30e581e8b2f2 /]# az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.98"
  }
}
`
Upgrade using `az upgrade` doesn't work for some reason
`
[root@30e581e8b2f2 /]# az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.0. Latest version available is 2.40.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.fcix.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: ridgewireless.mm.fcix.net
 * updates: mirrors.unifiedlayer.com
No packages marked for update
CLI upgrade failed or aborted.
`
What I have is latest apparently
`
[root@30e581e8b2f2 /]# yum list azure-cli --showduplicates
..
azure-cli.x86_64                             2.33.1-1.el7                             azure-cli
azure-cli.x86_64                             2.34.0-1.el7                             azure-cli
azure-cli.x86_64                             2.34.1-1.el7                             azure-cli
azure-cli.x86_64                             2.35.0-1.el7                             azure-cli
azure-cli.x86_64                             2.36.0-1.el7                             azure-cli
azure-cli.x86_64                             2.37.0-1.el7                             azure-cli
azure-cli.x86_64                             2.38.0-1.el7                             azure-cli
`

**Comment by FumingZhang** [comment] 2022-09-09 05:55
Hey @howardjones, @nikolaypopov, I've noticed that both of you are using Python3.6, and the `sre_compile` module in Python3.6 does not have `dis` function, which results in the error.

I've checked the code, `sre_compile.dis` is actually not used and was accidentally added in PR [#5295](https://github.com/azure/azure-cli-extensions/pull/5295). I'll remove the import and release a new version of aks-preview to fix the issue.

As a workaround, consider updating Python to a newer version such as 3.8. Support for 3.6 has ended at [23 Dec 2021](https://endoflife.date/python). Besides, the CI in both [azure-cli](https://github.com/Azure/azure-cli/pull/20865) and [azure-cli-extensions](https://github.com/Azure/azure-cli-extensions/pull/5218) has dropped tests for 3.6.

**Comment by FumingZhang** [comment] 2022-09-09 06:05
The fix is PR [#5330](https://github.com/Azure/azure-cli-extensions/pull/5330).

**Comment by howardjones** [comment] 2022-09-09 06:53
Technically, *Microsoft* are using Python 3.6 here - that's the private python environment that's installed by the azcli package itself :-) Thanks for the pointer! We are working to upgrade our Ansible execution environment.

**Comment by navba-MSFT** [comment] 2022-09-12 04:14
@howardjones The above PR has been merged and this is the milestone https://github.com/Azure/azure-cli-extensions/milestone/71 for you to keep track. We will now proceed with the closure of this thread. Please feel free to reopen if you need any further assistance. We would be happy to help.

**Closed by navba-MSFT** 2022-09-12 04:14 UTC
Labels: bug, customer-reported, AKS, CXP Attention, Auto-Assign
