### ISSUE TITLE
Azure Arc - az connectedk8s connect issue with microk8S

### ISSUE THREAD

**Issue by squasta** [Azure/azure-cli-extensions#2528] opened 2020-10-15 13:57 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
connectedk8s

### Description of issue (in as much detail as possible)

try to connect to Azure Arc for K8S my microk8s cluster. Got an error message about connectivity. Was able to do it in September on another microk8s (following the same procedure)

**Command executed**

**az connectedk8s connect --name microk8s-2 --resource-group RG-DC-Stan-Bry-2**

**Result :**

_Command group 'connectedk8s' is in preview. It may be changed/removed in a future release._
_Ensure that you have the latest helm version installed before proceeding._
_This operation might take a while..._

_Unable to verify connectivity to the Kubernetes cluster._
_If you are using AAD Enabled cluster, verify that you are able to access the cluster. Learn more at_ _https://aka.ms/arc/k8s/onboarding-aad-enabled-clusters_
_Error: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/networking.k8s.io/v1/ (Caused by_ _NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fa580b710>: Failed to establish a new connection: _[Errno 111] Connection refused',))__

**Environment :**
Ubuntu 20.04 LTS
microk8s v1.19
Helm Version:"v3.3.4"
az cli version 2.13.0
az extension k8sconfiguration version 0.1.8
az extension connectedk8s 0.2.6

-----

**Comment by ahmedsza** [comment] 2020-10-15 18:01
I had virtually the same error today with kind. I am on mobile now so don't have all the details 

Unable to verify connectivity to the Kubernetes cluster.

If you are using AAD Enabled cluster, verify that you are able to access the cluster. Learn more at https://aka.ms/arc/k8s/onboarding-aad-enabled-clusters

Error: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/networking.k8s.io/v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faec5c75908>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by ahmedsza** [comment] 2020-10-20 08:04
this was fixed by moving the latest version of the connectedk8s extension

**Closed** 2023-01-06 16:58 UTC
Labels: question, Service Attention, Connected Kubernetes
