### ISSUE TITLE
It seems like that "--remove" option doesn't work

### ISSUE THREAD

**Issue by KosukeHosoda** [Azure/azure-cli-extensions#1755] opened 2020-05-22 09:45 UTC
I tried to remove a FQDN from the Threat Intelligence Whitelist by "--remove" option.
But, it didn't work and error was output as below.
![image](https://user-images.githubusercontent.com/46177050/82655058-95a89880-9c5c-11ea-9f67-d205e18872c1.png)

Here is the series of commands that I used for test.
\---------------------------------------------------------------------------------
1. extend the feature
az extension add -n azure-firewall

2. create the list
az network firewall threat-intel-whitelist create -g FWGroup -n AzFW --ip-addresses 10.0.0.0 --fqdns www.bing.com *google.com

3. show the list
az network firewall threat-intel-whitelist show --resource-group FWGroup --name AzFW 

4. try to remove a FQDN from the list
az network firewall threat-intel-whitelist update --resource-group FWGroup --name AzFW --remove "ThreatIntel.Whitelist.FQDNs" 0

\---------------------------------------------------------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773c713c-34d2-c74c-8c58-5cf273cbb25a
* Version Independent ID: 0b6343a9-bbcd-2f54-b21e-cf9222c21e9f
* Content: [az network firewall threat-intel-whitelist](https://docs.microsoft.com/en-us/cli/azure/ext/azure-firewall/network/firewall/threat-intel-whitelist?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-firewall/network/firewall/threat-intel-whitelist.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-firewall/network/firewall/threat-intel-whitelist.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by KosukeHosoda** [comment] 2020-05-22 10:25
I tried "--set" option, too and the same error was outputted.
![image](https://user-images.githubusercontent.com/46177050/82658430-ebcc0a80-9c61-11ea-9f10-f50d77c88edb.png)

the commands
\------------------------------------------------------
1. extend the feature
az extension add -n azure-firewall

2. create the list
az network firewall threat-intel-whitelist create -g FWGroup -n AzFW --ip-addresses 10.0.0.0 --fqdns www.bing.com *google.com

3. show the list
az network firewall threat-intel-whitelist show --resource-group FWGroup --name AzFW

4. try to remove a FQDN from the list
az network firewall threat-intel-whitelist update --resource-group FWGroup --name AzFW --set "ThreatIntel.Whitelist.FQDNs=*google.com"

\------------------------------------------------------

**Comment by yonzhan** [comment] 2020-05-22 10:50
add to S171

**Comment by MyronFanQiu** [comment] 2020-05-25 02:56
Hi. Please try
`az network firewall threat-intel-whitelist update -g FWGroup -n AzFW --ip-addresses 10.0.0.0 --fqdns *google.com`

**Comment by KosukeHosoda** [comment] 2020-05-25 03:42
Thank you so much for the comment. I succeeded in removing a FQDN by your commands.

Could you confirm whether **"--remove"** option is available is not?

**Comment by MyronFanQiu** [comment] 2020-05-25 05:08
> Thank you so much for the comment. I succeeded in removing a FQDN by your commands.
> 
> Could you confirm whether **"--remove"** option is available or not?
> Also, I guess this option is for removing a FQDN/IP from the list. Am I right?

`--remove` and `--set` is a general support across azure cli commands to remove or set request payload directly. Along with service's development, if you cannot find native arguments, you could try `--remove` or `--set` until azure cli supports them in a native way. However, these two properties are quite special. The key name contains `.`. Currently, `--remove` and `--set` cannot deal with such scenarios.

**Comment by MyronFanQiu** [comment] 2020-05-29 09:08
close this issue since it's by design.

**Closed by MyronFanQiu** 2020-05-29 09:08 UTC
Labels: Network, question
