### ISSUE TITLE
az image copy - Fails copying blob to target account

### ISSUE THREAD

**Issue by ngrp-flightcentre-uk** [Azure/azure-cli-extensions#318] opened 2018-09-26 15:31 UTC
### Description
The following command fails

```
az image copy --source-resource-group "preprod-ngrp-emea" --source-type image --source-object-name "PreProd-EMEA-ESB01-image" --target-location "australiaeast" --target-resource-group "preprod-ngrp-apac" --target-name "PreProd-APAC-ESB01-image"
Getting os disk id of the source vm/image
Creating source snapshot
Getting sas url for the source snapshot
Creating resource group: image-copy-rg
Target location count: 1
Starting async process for all locations
australiaeast - Creating target storage account (can be slow sometimes)
australiaeast - Creating container in the target storage account
australiaeast - Copying blob to target storage account
command ended with an error: ['/opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'blob', 'copy', 'start', '--source-uri', None, '--destination-blob', 'PreProd-EMEA-ESB01-image_os_disk_snapshot.vhd', '--destination-container', 'snapshots', '--account-name', 'australiaeastv9we77wq0yq', '--sas-token', 'se=2018-09-26T16%3A06Z&sp=rwlacup&spr=https&sv=2018-03-28&ss=b&srt=sco&sig=sjWxL3ZNIX4Xc6BL1YtrZifZuhI4Pj2YWI2DWxa%2BZaE%3D', '--output', 'json']
```

The output of the following command (debug mode) is attached.
```
az image copy --source-resource-group "preprod-ngrp-emea" --source-type image --source-object-name "PreProd-EMEA-ESB01-image" --target-location "australiaeast" --target-resource-group "preprod-ngrp-apac" --target-name "PreProd-APAC-ESB01-image" --cleanup --debug 2>Downloads/azcopy-log.txt
```

The image to be copied is created from a virtual machine. OS type = Linux. Account type : Standard HDD.

[azcopy-log.txt](https://github.com/Azure/azure-cli-extensions/files/2420426/azcopy-log.txt)

-----

**Comment by tamirkamara** [comment] 2018-09-26 16:20
Hi @ngrp-flightcentre-uk 
This is caused by some change in the core azure-cli module: Azure/azure-cli#7416, looks like a fix in underway.
Also related to #314 @brianttu70

**Comment by adewaleo** [comment] 2018-09-27 20:43
Thanks for info @tamirkamara.

@ngrp-flightcentre-uk, is it ok to close this issue, as the fix should be available in the next release? 
Was the work around in #314 helpful?

**Comment by brianttu70** [comment] 2018-09-27 21:08
@adewaleo roll back version 45 of the CLI and all is good again...  I found this yesterday and reported it to Azure...

**Comment by adewaleo** [comment] 2018-09-27 22:17
Thanks @brianttu70  In that case, I'll be closing this issue. There is a temporary work around and the bug will be fixed in the next release.

**Closed by adewaleo** 2018-09-27 22:17 UTC
