### ISSUE TITLE
Multiline description

### ISSUE THREAD

**Issue by san7hos** [Azure/azure-cli-extensions#847] opened 2019-07-11 19:39 UTC
I am trying to create a powershell function that takes child items of an item and clones them under a different item. The function works except when I put multiline html to --description parameter, the description is empty. In history of the created item, I can see description being set as empty or empty line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5f488f-0ed7-6585-72c4-54095f30e1d3
* Version Independent ID: b1a48b12-cbb0-416a-1a71-2715d8dd8057
* Content: [az boards work-item](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/work-item?view=azure-cli-latest#ext-azure-devops-az-boards-work-item-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/boards/work-item.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/boards/work-item.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ishitam8** [comment] 2019-07-15 10:44
Hi @san7hos ,

I was not able to reproduce your issue.
Can you share the debug logs of the command you are trying to run [you would need to run the same command with --debug switch] ?
Also share the multi line html you are trying to set as description.

**Comment by geverghe** [comment] 2019-10-15 12:37
Hi @san7hos - I am closing this issue. Feel free to reopen this issue in case this is still a problem. Further, it would be super helpful for us if you could open any issue related to az devops | az pipelines | az artifacts | az repos | az boards on https://github.com/Azure/azure-devops-cli-extension/issues .

**Closed by geverghe** 2019-10-15 12:37 UTC
Labels: Question, extension/devops
