### ISSUE TITLE
Unable to load extension 'azure-devops' from Devops pipeline

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-cli-extensions#1381] opened 2020-03-12 07:24 UTC
###Extension Name :  Az Devops

Error:-
### WARNING: Unable to load extension 'azure-devops'. Use --debug for more information.

Issue Description : AZ devops extension is added in the agent and i can find it through Az --version locally. When i run the devops pipline with CLI Task, it throws me error Az devops command not found. Also i am getting warning, unable to load extension Ázure-Devops

PS C:\windows\system32> az --version
azure-cli                          2.1.0
command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
azure-devops                      0.17.0
'
![image](https://user-images.githubusercontent.com/42839520/76497193-8b9a3a80-6460-11ea-9ee3-570e9ecf8e0f.png)

**Comment by yungezz** [comment] 2020-03-12 12:14
hi @jayaakshayan how did you add az devops extension? could you pls try below?
```
az extension add azure-devops
```

**Comment by jayaakshayan** [comment] 2020-03-12 13:55
I have added like ” az extension add --name azure-devops”.

Do i want to try your method “ az extension add azure-devops”, does it make any difference.

**Comment by geverghe** [comment] 2020-04-03 15:43
This is duplicate of the issue https://github.com/Azure/azure-devops-cli-extension/issues/966 I am closing this from here. You can track progress in the issue mentioned.

**Closed by geverghe** 2020-04-03 15:43 UTC
Labels: Service Attention, extension/devops
