### ISSUE TITLE
"az devops extension install" failing with 500 errors

### ISSUE THREAD

**Issue by jkewley** [Azure/azure-cli-extensions#965] opened 2019-09-25 16:26 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
azure-devops 0.12.0

### Description of issue (in as much detail as possible)
Installation of extensions using the `azure-devops` extension is failing on the back end with 500 errors. 

```
PS C:\Users\MY_NAME> az devops extension install --org https://MY_ORG.visualstudio.com/ --extension-name "Veracode" --publisher-name "Veracode" --debug

Command arguments: ['devops', 'extension', 'install', '--org', 'https://MY_ORG.visualstudio.com/', '--extension-name', 'Veracode', '--publisher-name', 'Veracode', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x040B6078>, <function OutputProducer.on_global_arguments at 0x03FB0C90>, <function CLIQuery.on_global_arguments at 0x03FDFD68>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.009 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.007 seconds.
Loaded module 'apim' in 0.003 seconds.
Loaded module 'appconfig' in 0.004 seconds.
Loaded module 'appservice' in 0.009 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.010 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.003 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.004 seconds.
Loaded module 'container' in 0.003 seconds.
Loaded module 'cosmosdb' in 0.007 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.005 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.004 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.005 seconds.
Loaded module 'network' in 0.023 seconds.
Loaded module 'policyinsights' in 0.004 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.007 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'relay' in 0.004 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.006 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.003 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.026 seconds.
Loaded module 'vm' in 0.015 seconds.
Loaded all modules in 0.300 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Found 3 extensions: ['application-insights', 'azure-devops', 'subscription']
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.72 min_required=2.0.56 max_required=None
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Loaded extension 'application-insights' in 0.006 seconds.
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.72 min_required=2.0.49 max_required=None
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Loaded extension 'azure-devops' in 0.038 seconds.
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.72 min_required=None max_required=None
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Loaded extension 'subscription' in 0.006 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x041012B8>]
az_command_data_logger : command args: devops extension install --org {} --extension-name {} --publisher-name {} --debug
metadata file logging enabled - writing logs to 'C:\Users\MY_NAME\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x041371E0>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04137C00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04137CD8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04EFEFA8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03FB0CD8>, <function CLIQuery.handle_query_parameter at 0x03FDFDB0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04137C90>, <function handler at 0x04FD2D68>, <function DevCommandsLoader.post_parse_args at 0x054EF6A8>]
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
Extensions directory: 'C:\Users\MY_NAME\.azure\cliextensions'
az_command_data_logger : extension name: azure-devops
az_command_data_logger : extension version: 0.12.0
Getting credential: azdevops-cli:https://MY_ORG.visualstudio.com
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
PAT is present which can be used against this instance
Current cloud config:
AzureCloud


[Clipped **11** failures trying to get tokens for different tenants instead of using the PAT provided at `az devops login` (why?)]


Getting credential: azdevops-cli:https://MY_ORG.visualstudio.com
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
Creating connection with personal access token.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Current cloud config:
AzureCloud
Azure devops telemetry enabled.
Logging telemetry to azure devops server.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client : POST https://MY_ORG.visualstudio.com/_apis/CustomerIntelligence/Events
azext_devops.devops_sdk.connection : File cache hit for resources on: https://MY_ORG.visualstudio.com
azext_devops.devops_sdk.client : Request content: [{'area': 'AzureDevopsCli', 'feature': 'devops', 'properties': {'Command': 'extension install', 'Args': 'publisher_name extension_name organization', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': False, 'RepoPresentInCommand': False}}]
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http : Configuring redirects: allow=True, max=30
azext_devops.devops_sdk.client : File cache hit for options on: https://MY_ORG.extmgmt.visualstudio.com
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}/{publisherName}/{extensionName}/{version}
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
urllib3.connectionpool : Starting new HTTPS connection (1): MY_ORG.visualstudio.com:443
azext_devops.devops_sdk.client : POST https://MY_ORG.extmgmt.visualstudio.com/_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): MY_ORG.extmgmt.visualstudio.com:443
urllib3.connectionpool : https://MY_ORG.visualstudio.com:443 "POST /_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool : https://MY_ORG.extmgmt.visualstudio.com:443 "POST /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode HTTP/1.1" 500 315
urllib3.util.retry : Incremented Retry for (url='/_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retry: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode
urllib3.connectionpool : https://MY_ORG.extmgmt.visualstudio.com:443 "POST /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode HTTP/1.1" 500 315
urllib3.util.retry : Incremented Retry for (url='/_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retry: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode
urllib3.connectionpool : https://MY_ORG.extmgmt.visualstudio.com:443 "POST /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode HTTP/1.1" 500 315
urllib3.util.retry : Incremented Retry for (url='/_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retry: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode
urllib3.connectionpool : https://MY_ORG.extmgmt.visualstudio.com:443 "POST /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode HTTP/1.1" 500 315
msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='MY_ORG.extmgmt.visualstudio.com', port=443): Max retries exceeded with url: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode (Caused by ResponseError('too many 500 error responses',))
handling generic error
cli.azure.cli.core.util : request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='MY_ORG.extmgmt.visualstudio.com', port=443): Max retries exceeded with url: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode (Caused by ResponseError('too many 500 error responses',))
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='MY_ORG.extmgmt.visualstudio.com', port=443): Max retries exceeded with url: /_apis/ExtensionManagement/InstalledExtensionsByName/Veracode/Veracode (Caused by ResponseError('too many 500 error responses',))
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2562 in cache
telemetry.check : Negative: The C:\Users\MY_NAME\.azure\telemetry.txt was modified at 2019-09-25 12:08:39.816489, which in less than 600.000000 s
command ran in 10.371 seconds.

```
-----

**Comment by atbagga** [comment] 2019-10-03 05:28
The command succeeds with the extension ID but not with name. 
Reproducible with -
```
az devops extension install --extension-name veracode --publisher-name veracode --debug
```

Works fine with -
```
az devops extension install --extension-name veracode-vsts-build-extension --publisher-name veracode --debug
```

**Comment by yonzhan** [comment] 2019-10-07 10:15
@zikalino  please take a look.

**Comment by atbagga** [comment] 2019-10-21 05:13
Closing this issue since we are working on the issue we have created in our repo for tracking.

**Closed by atbagga** 2019-10-21 05:13 UTC
Labels: extension/devops

**Comment by carlosonunez** [comment] 2020-07-27 22:44
I'm actually seeing this behavior today.

This is the extension I want to install:

```sh
$: az devops extension search -q "Terraform" | jq '.[] | select(.publisher.publisherName|contains("labs")) | { name: .displayName, extensionId: .extensionId, description: .shortDescription, publisher: .publisher }'
{
  "name": "Terraform",
  "extensionId": "0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0",
  "description": "Install terraform and run terraform commands to manage resources on Azure, AWS and GCP.",
  "publisher": {
    "displayName": "Microsoft DevLabs",
    "flags": "verified",
    "publisherId": "caa2c5e9-7390-4371-a9f6-185f778db5d2",
    "publisherName": "ms-devlabs"
  }
}
```

But I get 500s upon trying to install it:

```
DEBUG: Command arguments: ['devops', 'extension', 'install', '--extension-id', '0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0', '--publisher-id', 'caa2c5e9-7390-4371-a9f6-185f778db5d2', '--organization', 'https://dev.azure.com/$project_id', '--debug']
DEBUG: Event: Cli.PreExecute []
DEBUG: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10c6535e0>, <function OutputProducer.on_global_arguments at 0x10c6c3670>, <function CLIQuery.on_global_arguments at 0x10c6dedc0>]
DEBUG: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'util', 'vm']
DEBUG: Loaded module 'acr' in 0.006 seconds.
DEBUG: Loaded module 'acs' in 0.007 seconds.
DEBUG: Loaded module 'advisor' in 0.002 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'ams' in 0.005 seconds.
DEBUG: Loaded module 'apim' in 0.002 seconds.
DEBUG: Loaded module 'appconfig' in 0.003 seconds.
DEBUG: Loaded module 'appservice' in 0.168 seconds.
DEBUG: Loaded module 'aro' in 0.005 seconds.
DEBUG: Loaded module 'backup' in 0.004 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'batch' in 0.034 seconds.
DEBUG: Loaded module 'batchai' in 0.003 seconds.
DEBUG: Loaded module 'billing' in 0.002 seconds.
DEBUG: Loaded module 'botservice' in 0.003 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'cdn' in 0.004 seconds.
DEBUG: Loaded module 'cloud' in 0.001 seconds.
DEBUG: Loaded module 'cognitiveservices' in 0.002 seconds.
DEBUG: Loaded module 'configure' in 0.002 seconds.
DEBUG: Loaded module 'consumption' in 0.003 seconds.
DEBUG: Loaded module 'container' in 0.002 seconds.
DEBUG: Loaded module 'cosmosdb' in 0.006 seconds.
DEBUG: Loaded module 'deploymentmanager' in 0.003 seconds.
DEBUG: Loaded module 'dla' in 0.004 seconds.
DEBUG: Loaded module 'dls' in 0.004 seconds.
DEBUG: Loaded module 'dms' in 0.003 seconds.
DEBUG: Loaded module 'eventgrid' in 0.003 seconds.
DEBUG: Loaded module 'eventhubs' in 0.004 seconds.
DEBUG: Loaded module 'extension' in 0.001 seconds.
DEBUG: Loaded module 'feedback' in 0.001 seconds.
DEBUG: Loaded module 'find' in 0.001 seconds.
DEBUG: Loaded module 'hdinsight' in 0.002 seconds.
DEBUG: Loaded module 'interactive' in 0.001 seconds.
DEBUG: Loaded module 'iot' in 0.004 seconds.
DEBUG: Loaded module 'iotcentral' in 0.002 seconds.
DEBUG: Loaded module 'keyvault' in 0.007 seconds.
DEBUG: Loaded module 'kusto' in 0.002 seconds.
DEBUG: Loaded module 'lab' in 0.003 seconds.
DEBUG: Loaded module 'managedservices' in 0.002 seconds.
DEBUG: Loaded module 'maps' in 0.002 seconds.
DEBUG: Loaded module 'monitor' in 0.007 seconds.
DEBUG: Loaded module 'natgateway' in 0.002 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'netappfiles' in 0.003 seconds.
DEBUG: Loaded module 'network' in 0.029 seconds.
DEBUG: Loaded module 'policyinsights' in 0.002 seconds.
DEBUG: Loaded module 'privatedns' in 0.004 seconds.
DEBUG: Loaded module 'profile' in 0.002 seconds.
DEBUG: Loaded module 'rdbms' in 0.007 seconds.
DEBUG: Loaded module 'redis' in 0.003 seconds.
DEBUG: Loaded module 'relay' in 0.003 seconds.
DEBUG: Loaded module 'reservations' in 0.002 seconds.
DEBUG: Loaded module 'resource' in 0.007 seconds.
DEBUG: Loaded module 'role' in 0.004 seconds.
DEBUG: Loaded module 'search' in 0.002 seconds.
DEBUG: Loaded module 'security' in 0.003 seconds.
DEBUG: Loaded module 'servicebus' in 0.006 seconds.
DEBUG: Loaded module 'servicefabric' in 0.003 seconds.
DEBUG: Loaded module 'signalr' in 0.002 seconds.
DEBUG: Loaded module 'sql' in 0.009 seconds.
DEBUG: Loaded module 'sqlvm' in 0.003 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'storage' in 0.034 seconds.
DEBUG: Loaded module 'util' in 0.001 seconds.
DEBUG: Loaded module 'vm' in 0.015 seconds.
DEBUG: Loaded all modules in 0.463 seconds. (note: there's always an overhead with the first module loaded)
DEBUG: Found 1 extensions: ['azure-devops']
DEBUG: Extension compatibility result: is_compatible=True cli_core_version=2.8.0 min_required=2.2.0 max_required=None
DEBUG: Extensions directory: '/Users/cn/.azure/cliextensions/azure-devops'
DEBUG: Loaded extension 'azure-devops' in 0.024 seconds.
DEBUG: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10cbfc670>]
DEBUG: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10cc1de50>]
DEBUG: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10cc58790>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10cc588b0>]
DEBUG: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10dabbdc0>]
DEBUG: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10c6c3700>, <function CLIQuery.handle_query_parameter at 0x10c6dee50>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10cc58820>, <function handler at 0x10dc19af0>, <function DevCommandsLoader.post_parse_args at 0x10e50c820>]
DEBUG: PAT is present which can be used against this instance
DEBUG: Current cloud config:
AzureCloud
DEBUG: trying to get token (temp) for tenant 48994235-9df2-46eb-bf13-e3d17ee26fbf and user 6741acf7-6d71-44d5-9ac8-6ff2eb090c3d
DEBUG: attempting to read file /Users/cn/.azure/accessTokens.json as utf-8-sig
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - Authority:Performing instance discovery: ...
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - Authority:Performing static instance discovery
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - Authority:Authority validated via static instance discovery
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - TokenRequest:Getting token from cache with refresh if necessary.
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
DEBUG: adal-python : ccbe4f45-e3d4-43c2-93fe-7737e548540f - CacheDriver:Found 0 potential entries.
DEBUG: not able to get token from az login
DEBUG: Could not retrieve token from local cache. Please run 'az login'.
Traceback (most recent call last):
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 157, in get_token_from_az_login
    auth_token = profile.get_access_token_for_resource(user, tenant, '499b84ac-1321-427f-aa17-267ca6975798')
  File "/usr/local/Cellar/azure-cli/2.8.0/libexec/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 524, in get_access_token_for_resource
    _, access_token, _ = self._creds_cache.retrieve_token_for_user(
  File "/usr/local/Cellar/azure-cli/2.8.0/libexec/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 1016, in retrieve_token_for_user
    raise CLIError("Could not retrieve token from local cache.{}".format(
knack.util.CLIError: Could not retrieve token from local cache. Please run 'az login'.
DEBUG: instance recieved in validate_token_for_instance https://dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: instance processed in validate_token_for_instance https://dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache : Loading cache file: /Users/cn/.azure-devops/python-sdk/cache/resources.json
DEBUG: azext_devops.devops_sdk._file_cache : attempting to read file /Users/cn/.azure-devops/python-sdk/cache/resources.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.connection : File cache hit for resources on: https://dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache : Loading cache file: /Users/cn/.azure-devops/python-sdk/cache/options.json
DEBUG: azext_devops.devops_sdk._file_cache : attempting to read file /Users/cn/.azure-devops/python-sdk/cache/options.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.client : File cache hit for options on: https://dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: azext_devops.devops_sdk.client : Route template: _apis/{resource}/{*projectId}
DEBUG: azext_devops.devops_sdk.client : Api version '5.0'
DEBUG: azext_devops.devops_sdk.client : GET https://dev.azure.com/$project_id/_apis/projects?stateFilter=all&$top=1&$skip=0
DEBUG: azext_devops.devops_sdk.client : Request content: None
DEBUG: msrest.universal_http : Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http : Configuring proxies: ''
DEBUG: msrest.universal_http : Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): dev.azure.com:443
DEBUG: urllib3.connectionpool : https://dev.azure.com:443 "GET /$project_id/_apis/proje
cts?stateFilter=all&$top=1&$skip=0 HTTP/1.1" 401 307
DEBUG: azext_devops.devops_sdk.client : Response content: b'{"$id":"1","innerException":null,"message":"TF400813: The user \'\' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}'
DEBUG: msrest.exceptions : TF400813: The user '' is not authorized to access this resource.
DEBUG: TF400813: The user '' is not authorized to access this resource.
Traceback (most recent call last):
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 93, in validate_token_for_instance
    core_client.get_projects(state_filter='all', top=1, skip=0)
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/v5_0/core/core_client.py", line 140, in get_projects
    response = self._send(http_method='GET',
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 90, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "/Users/cn/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 233, in _handle_error
    raise AzureDevOpsServiceError(wrapped_exception)
azext_devops.devops_sdk.exceptions.AzureDevOpsServiceError: TF400813: The user '' is not authorized to access this resource.
DEBUG: Failed to connect using provided credentials
DEBUG: invalid token obtained for tenant 48994235-9df2-46eb-bf13-e3d17ee26fbf
INFO: received PAT from environment variable
INFO: Creating connection with personal access token.
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: Azure devops telemetry disabled.
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.connection : File cache hit for resources on: https://dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.client : File cache hit for options on: https://extmgmt.dev.azure.com/brchsa96k7ufs0sohafule96piiir8et
DEBUG: azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}/{publisherName}/{extensionName}/{version}
DEBUG: azext_devops.devops_sdk.client : Api version '5.0-preview.1'
DEBUG: azext_devops.devops_sdk.client : POST https://extmgmt.dev.azure.com/$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0
DEBUG: azext_devops.devops_sdk.client : Request content: None
DEBUG: msrest.universal_http : Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http : Configuring proxies: ''
DEBUG: msrest.universal_http : Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): extmgmt.dev.azure.com:443
DEBUG: urllib3.connectionpool : https://extmgmt.dev.azure.com:443 "POST /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0 HTTP/1.1" 500 371
DEBUG: urllib3.util.retry : Incremented Retry for (url='/$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
DEBUG: urllib3.connectionpool : Retry: /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0
DEBUG: urllib3.connectionpool : https://extmgmt.dev.azure.com:443 "POST /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0 HTTP/1.1" 500 371
DEBUG: urllib3.util.retry : Incremented Retry for (url='/$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
DEBUG: urllib3.connectionpool : Retry: /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0
DEBUG: urllib3.connectionpool : https://extmgmt.dev.azure.com:443 "POST /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0 HTTP/1.1" 500 371
DEBUG: urllib3.util.retry : Incremented Retry for (url='/$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
DEBUG: urllib3.connectionpool : Retry: /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0
DEBUG: urllib3.connectionpool : https://extmgmt.dev.azure.com:443 "POST /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0 HTTP/1.1" 500 371
DEBUG: msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='extmgmt.dev.azure.com', port=443): Max retries exceeded with url: /$project_id/_apis/ExtensionManagement/InstalledExtensionsByName/caa2c5e9-7390-4371-a9f6-185f778db5d2/0cd0a1f5-ca4c-4f83-ba90-e7c0e65f23d0 (Caused by ResponseError('too many 500 error responses'))
DEBUG: handling generic error
```

This works just fine through the UI, however.
