### ISSUE TITLE
az aks upgrade still prompts for yes/no when --yes flag was specified

### ISSUE THREAD

**Issue by weng271190436** [Azure/azure-cli-extensions#1328] opened 2020-02-28 19:30 UTC
I made a request:

```powershell
az aks upgrade -g "resource-group" -n "cluster-name" --kubernetes-version 1.14.8 --yes
```

I got prompted with the message:
```powershell
Since control-plane-only argument is not specified, this will upgrade the control plane AND all nodepools to version 1.14.8. Continue? (y/N):
```

Expected behavior is that the `az aks upgrade` command should run without prompting if I specify the --yes flag.

A screenshot:
![image](https://user-images.githubusercontent.com/6925089/75581164-d7d78a80-5a1d-11ea-96df-7cba987fe3fb.png)

Update:
I didn't post the az cli version originally:
![image](https://user-images.githubusercontent.com/6925089/75598982-6c111400-5a55-11ea-9ab5-ff1cc62f62a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea52f6a-7414-7aa2-3708-7b802f243a16
* Version Independent ID: cf003f17-b9f7-04d4-89c2-770273b40533
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/aks-preview/aks.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment] 2020-02-29 02:03
thanks for reporting, we'll have a look

**Comment by tdihp** [comment] 2020-02-29 02:48
Duplicate of https://github.com/Azure/azure-cli/issues/11099

**Comment by navba-MSFT** [comment] 2022-02-09 10:29
@weng271190436 Apologies for the late reply. This issue seems to be fixed in this PR https://github.com/Azure/azure-cli/pull/13741. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the CLI and let me know if you still face this issue ? Also this github issue is open for quite sometime. Please let me know if you still need any assistance on this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-02-12 07:35
@weng271190436 This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Closed** 2022-03-06 08:00 UTC
Labels: AKS, Service Attention, needs-author-feedback, no-recent-activity
