### ISSUE TITLE
aks-preview 0.4.71: az aks update with --attach-acr failed if monitoring addon not installed

### ISSUE THREAD

**Issue by marywhitney** [Azure/azure-cli-extensions#2898] opened 2021-01-14 05:00 UTC
## Describe the bug
In a new AKS cluster without monitoring enabled, try to attach an ACR, and the command errs.

**Command Name**
This is the command that erred.
```
az aks update \
    --name $AKS_CLUSTER_NAME \
    --resource-group $RESOURCE_GROUP \
    --attach-acr $ACR_NAME
```

Extension Name: aks-preview. Version: 0.4.71.`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1495, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

In an environment with aks-preview 0.4.71 installed, deploy a new lab AKS cluster following the steps almost identical to this workshop, using Azure cloud shell: <https://docs.microsoft.com/en-us/learn/modules/aks-workshop/02-deploy-aks>

I worked around the error by enabling the monitoring addon with the command below. After that, the command with --attach-acr worked.

```
az aks enable-addons \
    --resource-group $RESOURCE_GROUP \
    --name $AKS_CLUSTER_NAME \
    --addons monitoring \
    --workspace-resource-id $WORKSPACE_ID
```

## Expected Behavior
Grant the AKS service principal access to the ACR.

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
aks-preview 0.4.71
k8sconfiguration 0.2.2
ai-examples 0.2.5
azure-cli-ml 1.19.0

```
## Additional Context

I did the exact same steps successfully before this error, but three things changed:
* I ran this update. I don't know what aks-preview version I had when the steps succeeded, the first time through. 
`az extension update --name aks-preview
* I installed this extension, version 0.2.2:
`az extension add -n k8sconfiguration
* I re-created the cluster in eastus, not centralus.

**Comment by yonzhan** [comment] 2021-01-14 05:21
aks

**Comment by RakeshMohanMSFT** [comment] 2022-11-11 05:18
Duplicate of https://github.com/Azure/azure-cli-extensions/issues/2898

**Closed by RakeshMohanMSFT** 2022-11-11 05:18 UTC
Labels: extension/aks-preview, AKS, Service Attention, Error Handling
