### ISSUE TITLE
Logging in with service principal?

### ISSUE THREAD

**Issue by aodj** [Azure/azure-cli-extensions#1274] opened 2020-02-14 10:18 UTC
I'm attempting to use the azure-devops extension to download universal artifacts. This works with my personal account, but when I attempt to use a service principal I've created for scripting purposes, it fails to log in.

When attempting to download after logging in (with az login) I get the error message:

```bash
Failed to update Universal Packages tooling.
 TF400813: Resource not available for anonymous access. Client authentication required.
```

However, if I attempt to subsequently log in with (with az devops login) I get prompted for my PAT, which I don't have for the service principal.
```bash
$ az login --service-principal --username foo --password bar --tenant hamandeggs
[
  {
    "cloudName": "AzureCloud",
    ...
  }
]
$ az devops login
Token:
```

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9e855a-abc5-14d9-ba73-4ab527ffee16
* Version Independent ID: 85a46540-4b25-94f4-2c0e-29e1f8fefe35
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest#ext-azure-devops-az-devops-login)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by aodj** [comment] 2020-02-14 15:24
Ah, after some further research I see that service principals simply don't work with Azure DevOps at all ([link to GitHub issue](https://github.com/Azure/azure-devops-cli-extension/issues/905)).

**Comment by yungezz** [comment] 2020-02-15 04:05
thanks for reporting the issue, we'll have a look

**Comment by arrownj** [comment] 2020-02-17 01:50
Hi @gauravsaralMs , could you please help with this ?

**Comment by geverghe** [comment] 2020-04-03 16:12
As @aodj  pointed out, this is a duplicate of https://github.com/Azure/azure-devops-cli-extension/issues/905 . As @aodj has mentioned, az login via service principal is not supported for devops commands. You would need to use a PAT token in this case. I have also raised a PR to fix the issue in our documentation. 

I am closing this issue as we will be recording any future updates with respect to support for service principals in this issue - https://github.com/Azure/azure-devops-cli-extension/issues/905

**Closed by geverghe** 2020-04-03 16:12 UTC
Labels: Service Attention, extension/devops
