### ISSUE TITLE
az aks update --enable-defender doesn't work with aks-preview extension

### ISSUE THREAD

**Issue by TomGeske** [Azure/azure-cli-extensions#5092] opened 2022-07-08 11:49 UTC
## Describe the bug

**Command Name**
`az aks update
Extension Name: aks-preview. Version: 0.5.87.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'AKSPreviewManagedClusterModels' object has no attribute 'ManagedClusterSecurityProfileAzureDefender'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/thomasge/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 798, in aks_update
    mc = aks_update_decorator.update_mc_profile_preview()
  File "/home/thomasge/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 1942, in update_mc_profile_preview
    mc = self.update_mc_profile_default()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5631, in update_mc_profile_default
    mc = self.update_defender(mc)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5552, in update_defender
    defender = self.context.get_defender_config()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 3672, in get_defender_config
    azure_defender = self.models.ManagedClusterSecurityProfileAzureDefender(enabled=enable_defender)
AttributeError: 'AKSPreviewManagedClusterModels' object has no attribute 'ManagedClusterSecurityProfileAzureDefender'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --enable-defender -g {} -n {}`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
subscription 0.1.5
containerapp 0.3.7
aks-preview 0.5.87
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-07-08 12:48
route to CXP team

**Comment by navba-MSFT** [comment] 2022-07-11 02:28
@TomGeske Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-07-12 04:21
@TomGeske The above PR has been created to address this issue. In the meantime, if you have any questions, please feel free to ask.

**Comment by TomGeske** [comment] 2022-07-13 13:19
@navba-MSFT: I see PR being merged. Kindly advise when the new aks-preview version becomes available for testing.

**Comment by navba-MSFT** [comment] 2022-07-13 13:25
@TomGeske This should be released in 2022-08-02 See this: https://github.com/Azure/azure-cli-extensions/milestone/69

**Comment by navba-MSFT** [comment] 2022-07-14 03:32
@TomGeske We will now proceed with closure of this thread. Please feel free to reopen if you have any follow-up questions. We would be happy to help.

**Closed by navba-MSFT** 2022-07-14 03:32 UTC
Labels: bug, AKS, needs-author-feedback, CXP Attention, Auto-Assign

**Comment by FumingZhang** [comment] 2022-07-14 07:33
The issue is fixed in the latest version of aks-preview (**0.5.91**).

This problem can be solved by updating to the latest version of aks-preview without waiting for the new version of azure-cli release.
