### ISSUE TITLE
az k8s-extension extension-types command errors out with "takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by Remigijus-D** [Azure/azure-cli-extensions#5324] opened 2022-09-08 10:19 UTC
## Describe the bug

**Command Name**
`az k8s-extension extension-types list-by-location
Extension Name: k8s-extension. Version: 1.3.3.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cf_k8s_extension() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\RemigijusDaujotas\.azure\cliextensions\k8s-extension\azext_k8s_extension\_client_factory.py", line 29, in cf_k8s_location_extension_types_operation
    return cf_k8s_extension(cli_ctx, consts.EXTENSION_TYPE_API_VERSION).location_extension_types
TypeError: cf_k8s_extension() takes 1 positional argument but 2 were given

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az k8s-extension extension-types list-by-location --location westeurope`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0 *

Extensions:
azure-devops 0.25.0
k8s-extension 1.3.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2022-09-08 13:10
route to CXP team

**Comment by RakeshMohanMSFT** [comment] 2022-09-13 09:00
@Remigijus-D Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment] 2022-09-19 07:21
Duplicate of https://github.com/Azure/azure-cli-extensions/issues/5356

**Closed by RakeshMohanMSFT** 2022-09-19 07:21 UTC
Labels: extension/aks-preview, customer-reported, AKS, CXP Attention
