### ISSUE TITLE
closing az aks browse session shows error (running through WSL 1 bash)

### ISSUE THREAD

**Issue by ameetkonnur** [Azure/azure-cli-extensions#921] opened 2019-08-27 04:33 UTC
## Describe the bug

**Command Name**
`az aks browse
Extension Name: aks-preview. Version: 0.4.4.`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab864cfe80>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
...
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab864cfe80>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Linux-4.4.0-17134-Microsoft-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.71

Extensions:
aks-preview 0.4.4
alias 0.5.2
azure-devops 0.11.0
log-analytics 0.1.3
resource-graph 0.1.8

```

**Comment by seanmck** [comment] 2019-09-05 05:27
Duplicate of azure/azure-cli#7686

**Closed by seanmck** 2019-09-05 05:27 UTC
Labels: AKS, Service Attention, customer-reported
