### ISSUE TITLE
az webapp connection create sql fails

### ISSUE THREAD

**Issue by pavansinguluri** [Azure/azure-cli-extensions#5959] opened 2023-03-08 06:08 UTC
### **This is autogenerated. Please review and update as needed.**

**Command Name**
`az webapp connection create sql
Extension Name: serviceconnector-passwordless. Version: 0.1.0.`

**Errors:**
```
The behavior of this command has been altered by the following extension: serviceconnector-passwordless
Connection name is not specified, use generated one: --connection 123
Checking if WebApp enables System Identity...
Connecting to database...
The command failed with an unexpected error. Here is the traceback:
dlopen(/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/pyodbc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/pavankumarsinguluri/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py", line 28, in connection_create_ext
    return connection_create_func(cmd, client, connection_name, client_type,
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/serviceconnector/custom.py", line 459, in connection_create_func
    new_auth_info = enable_mi_for_db_linker(
  File "/Users/pavankumarsinguluri/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 88, in enable_mi_for_db_linker
    target_handler.create_aad_user()
  File "/Users/pavankumarsinguluri/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 336, in create_aad_user
    self.create_aad_user_in_sql(connection_args, query_list)
  File "/Users/pavankumarsinguluri/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 375, in create_aad_user_in_sql
    import pyodbc
ImportError: dlopen(/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/pyodbc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp connection create sql --resource-group {} --name {} --target-resource-group {} --server {} --database {} --client-type {} --system-identity`

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.46.0

Extensions:
serviceconnector-passwordless 0.1.0
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment] 2023-03-08 08:28
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-15 21:36
@pavansinguluri I am not able to reproduce this issue. You have be having issue with pyodbc on your Mac Machine.  Please can you try refer to this [GitHub discussion ](https://github.com/MicrosoftDocs/azure-docs/issues/105412)if this fixes your issue.

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-20 22:00
@pavansinguluri Please let me know if you are still having issues.

**Comment by SaurabhSharma-MSFT** [comment] 2023-03-29 01:08
@pavansinguluri We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2023-03-29 01:08 UTC
Labels: question, extension/webapp, customer-reported, App Services, Web Apps, needs-author-feedback, no-recent-activity, CXP Attention, Auto-Assign
