### ISSUE TITLE
The command `az aks upgrade` prompts for user input when you provide `--yes`

### ISSUE THREAD

**Issue by epierotto** [Azure/azure-cli-extensions#982] opened 2019-10-07 10:08 UTC
## Describe the bug

**Command Name**
`az aks upgrade`

**Errors:**
The command is prompting for user input when `--yes` is provided.
```bash
Since control-plane-only argument is not specified, this will upgrade the control plane AND all nodepools to version 1.14.5. Continue? (y/N):
```

## To Reproduce:
- `az aks upgrade --resource-group {} --name {} --kubernetes-version {} --no-wait --yes`

## Expected Behavior
Provided the flag `--yes` I expect no user input needed to execute the command.
```bash
Since control-plane-only argument is not specified, this will upgrade the control plane AND all nodepools to version 1.14.5. Continue? (y/N):
```

## Environment Summary
```
Linux-4.14.131-linuxkit-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.74

Extensions:
aks-preview 0.4.17

```

**Comment by epierotto** [comment] 2019-10-22 10:26
If the `upgrade` command by default prompts a [confirmation message](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/commands.py#L49), why are you guys prompting a second confirmation [message](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/custom.py#L1250)?

If further explanation needs to be provided to the user, to prevent unintentional operations, that could be done on the first prompt message.
I see that you have this pattern of prompting twice in few commands there, but I would like to know the reason for doing so.

Also since that you have [NoTTYException](https://github.com/Azure/azure-cli-extensions/blob/master/src/aks-preview/azext_aks_preview/custom.py#L33), that prevents some simple automation like:
` yes | az aks upgrade...` or `printf 'y\n' | az aks upgrade...`

**Comment by ConnorDickson** [comment] 2020-02-06 15:59
Any update on this?

**Comment by tdihp** [comment] 2020-03-02 09:52
Duplicate of https://github.com/Azure/azure-cli/issues/11099,

For a workaround @epierotto : `az resource update --ids <aks_resource_id> --set 'properties.kubernetesVersion=<k8s_version>'--set 'properties.agentPoolProfiles[0].orchestratorVersion=<k8s_version>'
`

**Comment by navba-MSFT** [comment] 2022-02-09 10:21
@epierotto Apologies for the late reply. This issue seems to be fixed in this PR [#13741 ](https://github.com/Azure/azure-cli/pull/13741). Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the CLI and let me know if you still face this issue ?  Also this github issue is open for quite sometime. Please let me know if you still need any assistance on this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-02-12 07:34
@epierotto This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by epierotto** [comment] 2022-02-12 18:13
Hi, it’s been a while since I opened this issue and I used the workaround
setting a cluster property. If you consider that the problem was solved
with that commit please close this issue.

Regards
Exequiel

**Comment by navba-MSFT** [comment] 2022-02-15 11:57
@epierotto Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-02-15 11:57 UTC
Labels: extension/aks-preview, customer-reported, AKS, Service Attention
