### ISSUE TITLE
az devops invoke and DELETE

### ISSUE THREAD

**Issue by pieterv-icloud-com** [Azure/azure-cli-extensions#757] opened 2019-06-10 18:04 UTC
## Describe the bug

Trying to delete a variable group, alway failing with the errr
or

**Command Name**
`az devops invoke
Extension Name: azure-devops. Version: 0.10.0.`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 609, in _run_job
    cmd_copy.exception_handler(ex)
...
azure/cli/core/__init__.py, ln 453, in default_command_handler
    return op(**command_args)
azext_devops/dev/team/invoke.py, ln 112, in invoke
    if 'json' in response.headers.get("content-type") and not out_file:
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops invoke --area {} --resource {} --query-parameters {} --route-parameters {} --http-method {} --api-version {} --accept-media-type {} --out-file {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

Extensions:
azure-devops 0.10.0

```

**Comment by atbagga** [comment] 2019-06-12 04:59
@pieterv-icloud-com Thank you for reporting the issue. The delete operation should succeed even though the command fails after performing the delete operation. 

This is a duplicate of https://github.com/Azure/azure-devops-cli-extension/issues/655.
This was fixed in https://github.com/Azure/azure-devops-cli-extension/pull/656 last week. The fix should be available in next release of Azure-devops extension version 0.11.0. 

ETA would be sometime next week.

**Closed** 2019-06-14 08:14 UTC
Labels: extension/devops
