### ISSUE TITLE
az containerapp logs show failing with KeyError: logStreamEndpoint

### ISSUE THREAD

**Issue by samavos** [Azure/azure-cli-extensions#5519] opened 2022-11-05 20:52 UTC
## Describe the bug

No obvious additional setup - just trying to get the logs of any containerapps.

**Command Name**
`az containerapp logs show
Extension Name: containerapp. Version: 0.3.13.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'logStreamEndpoint'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/home/sam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2478, in stream_containerapp_logs
    logstream_endpoint = token_response["properties"]["logStreamEndpoint"]
KeyError: 'logStreamEndpoint'

```

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az containerapp logs show -n {} -g {}`

## Environment Summary
```
Linux-5.15.0-48-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0 *

Extensions:
ssh 1.1.3
containerapp 0.3.13

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by samavos** [comment] 2022-11-05 20:53
Seems to be a duplicate of #5518

**Comment by yonzhan** [comment] 2022-11-06 01:32
route to CXP team

**Comment by navba-MSFT** [comment] 2022-11-07 05:49
Duplicate of https://github.com/Azure/azure-cli-extensions/issues/5518 .

Please track the progress in the above thread.

**Closed by navba-MSFT** 2022-11-07 05:49 UTC
Labels: question, customer-reported, CXP Attention, Auto-Assign, ContainerApp
