### ISSUE TITLE
How to set accepted protocols to both HTTP and HTTPS

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli-extensions#1503] opened 2020-04-04 09:21 UTC
The docs state that `--accepted-protocols` takes a "space separated list", I've tried every combination and it doesn't work. I just get BadRequest - `"Value blah is not allowed for property 'Frontdoor.RoutingRules.AcceptedProtocols'"`

I've also tried a comma separated list, I don't get any error but the setting is never changed

Please advise how to set Accepted Protocols to both HTTP *and* HTTPS as you can in the portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc41d7b5-ab21-fe9b-2f2e-93ac02e5af86
* Version Independent ID: 67398425-8b96-f515-72af-22255ea1ae49
* Content: [az network front-door routing-rule](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment] 2020-04-04 11:57
add to S169

**Comment by yonzhan** [comment] 2020-05-02 14:19
add to S171

**Comment by MyronFanQiu** [comment] 2020-06-05 03:23
@benc-uk Hi. I just tried to create a routing rule and it works. Could you please try `--accepted-protocols Http Https`?
```
az network front-door routing-rule create -f clifrontdoor20200605 -g 20200605 -n rule1 --frontend-endpoints DefaultFrontendEndpoint --route-type Forward --backend-pool DefaultBackendPool --patterns /forward1 --accepted-protocols Http Https --debug
```

**Comment by MyronFanQiu** [comment] 2020-06-16 08:56
closed this issue since cannot reproduce. Feel free to open new issue if you still encounter this one.

**Closed by MyronFanQiu** 2020-06-16 08:56 UTC
Labels: Feature Request, Network, OKR3.2 Candidate, feature-request
