### ISSUE TITLE
Fail to  "az devops login --organization https://msazure.visualstudio.com"

### ISSUE THREAD

**Issue by wangglei** [Azure/azure-cli-extensions#748] opened 2019-06-06 23:09 UTC
## Describe the bug

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.10.0.`

**Errors:**
```
Failed to unlock the collection!
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure-devops/keyring/backends/SecretService.py, ln 64, in get_password
    collection = self.get_preferred_collection()
azure-devops/keyring/backends/SecretService.py, ln 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login --organization {}`

## Environment Summary
```
Linux-4.18.0-20-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.66

Extensions:
azure-devops 0.10.0

```

**Comment by atbagga** [comment] 2019-06-12 05:14
Are you running the commands interactively? if yes, you can try login through ```az login```. 

For automation use case PAT is the only option hence you will need ```az devops login```. The issue seems to be due to the external library (Keyring) support on your linux version, which we use to store the PAT token securely on the machine. While I take a look at it here is a workaround which will unblock you. 

**Workaround:** You can set the PAT token in the environment variable AZURE_DEVOPS_EXT_PAT which is an alternative to doing a ```az devops login```.

**Comment by atbagga** [comment] 2019-06-13 05:44
@wangglei Please try out the above and let us know if it helped.

**Comment by wangglei** [comment] 2019-06-13 19:25
@atbagga Yes! This workaround worked for me.

**Comment by ishitam8** [comment] 2019-07-15 07:00
Hi @wangglei ,

I am unable to reproduce your issue locally. Can you share the debug logs ?
Run the same command with --debug switch.
`az devops login --organization <ORG_URL> --debug`

Also, share the version of keyring and keyrings.alt (if any) package available on your system
`pip list`

**Comment by geverghe** [comment] 2019-10-15 12:41
@wangglei -  I am closing this issue. Feel free to reopen the issue in case it does not answer your query. Would be super helpful for us if you could open any issue related to az devops | az pipelines | az artifacts | az repos | az boards on https://github.com/Azure/azure-devops-cli-extension/issues .

**Closed by geverghe** 2019-10-15 12:41 UTC
Labels: extension/devops
