### ISSUE TITLE
[db-up] cannot be installed on azure-cli docker image

### ISSUE THREAD

**Issue by adewaleo** [Azure/azure-cli-extensions#743] opened 2019-06-05 03:39 UTC
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

db-up

## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- docker run -it mcr.microsoft.com/azure-cli:latest
- `az extension add -n {}`

## Environment Summary
```
Linux-4.9.125-linuxkit-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.66

```
## Additional Context

Output from --debug

```Running setup.py (path:/tmp/pip-build-cdq8frjc/psycopg2-binary/setup.py) egg_info for package psycopg2-binary
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cdq8frjc/psycopg2-binary/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cdq8frjc/psycopg2-binary/

Command '['/usr/local/bin/python', '-m', 'pip', 'install', '--target', '/root/.azure/cliextensions/db-up', '/tmp/tmpb2nn70fd/db_up-0.1.11-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Pip failed so deleting anything we might have installed at /root/.azure/cliextensions/db-up
```

-----

**Comment by adewaleo** [comment] 2019-06-05 03:41
cc: @yugangw-msft @devigned @limingu

**Comment by yonzhan** [comment] 2020-06-13 12:28
add to S173

**Comment by Juliehzl** [comment] 2020-07-14 07:21
@fengzhou-msft  could you help take a look?

**Comment by Juliehzl** [comment] 2020-07-14 07:23
dupe of https://github.com/Azure/azure-cli-extensions/issues/743

**Comment by Juliehzl** [comment] 2020-07-14 07:23
please try to install again

**Closed by Juliehzl** 2020-07-14 07:23 UTC
Labels: OKR3.4 Candidate, enhancement
