### ISSUE TITLE
aks-preview v 0.4.30. Command 'az aks nodepool add' fails  with --spot_max_price can only be set when --priority is Spot error

### ISSUE THREAD

**Issue by aleksandrshvets** [Azure/azure-cli-extensions#1300] opened 2020-02-20 15:32 UTC
az --version
azure-cli                          2.1.0
command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
aks-preview                       0.4.30

Steps to reproduce:
`az aks nodepool add --resource-group rg --name wpool1 --cluster-name cl --kubernetes-version 1.15.5 --os-type Windows --node-osdisk-size 64 --node-vm-size Standard_E4as_v4 --node-count 1 --no-wait --zones 1 2 3`

Result:
The behavior of this command has been altered by the following extension: aks-preview
--spot_max_price can only be set when --priority is Spot

Current workaround:
aks-preview v 0.4.29 works fine but it is not easy to get it

**Comment by dariuszbz** [comment] 2020-02-20 16:42
Hi,

I have the same issue (!) so:
aks-preview v 0.4.29 works fine but it is not easy to get it

how did you get it?

**Comment by jagdeepgithub** [comment] 2020-02-20 17:09
I encountered same issue, while its getting Triaged/Fixed, it will help if you can tell how to get aks-preview v0.4.29.

**Comment by dariuszbz** [comment] 2020-02-20 17:16
I found:
az extension remove -n aks-preview
az extension add --source https://azurecliaks.blob.core.windows.net/azure-cli-extension/aks_preview-0.4.29-py2.py3-none-any.whl

**Comment by dariuszbz** [comment] 2020-02-24 10:05
Hi developer team. Do you have any update on this?

**Comment by greggbjensen** [comment] 2020-02-24 20:15
We just ran into this same issue still with v0.4.32, and had to go back to v0.4.29.

**Comment by dariuszbz** [comment] 2020-02-25 11:02
it works only with 0.4.29. They made some changes to introduce scoping (like AWK K8s) on vmss - and here we have problems :). I hope the dev team will update this issue to let us know 'it's fixed'.

**Comment by jakaruna-MSFT** [comment] 2020-02-27 09:23
@jluk Please add your comments

**Comment by jluk** [comment] 2020-02-27 19:13
This should be resolved in v0.4.31, please update to the latest preview extension and try again.

The fix made is here: https://github.com/Azure/azure-cli-extensions/pull/1304

We are not able to reproduce with a version greater than that. Closing as resolved, but if you are producing this error on v0.4.33 please comment and we can revisit.

**Closed by jluk** 2020-02-27 19:13 UTC
Labels: Service Attention, extension/aks-preview
