### ISSUE TITLE
Creating a data factory with Azure CLI triggers error

### ISSUE THREAD

**Issue by juliakm** [Azure/azure-cli-extensions#2019] opened 2020-07-14 16:31 UTC
This was my initial command:

```    
az datafactory factory create \
        --name data-factory-cicd \
        --resource-group $rgName
```
## Describe the bug

**Command Name**
`az datafactory factory create
Extension Name: datafactory. Version: 0.1.0.`

**Errors:**
```
'expiresIn'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
    result = func(*args, **kwargs)
core/pipeline/policies/_authentication.py, ln 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
azure/cli/core/adal_authentication.py, ln 64, in get_token
    return AccessToken(token, int(full_token['expiresIn'] + time.time()))
KeyError: 'expiresIn'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory factory create --name {} --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0 *

Extensions:
databricks 0.4.0
datafactory 0.1.0

```

**Comment by yonzhan** [comment] 2020-07-14 22:25
datafactory

**Comment by fengzhou-msft** [comment] 2020-10-24 09:53
Duplicate of #1900. A fix is released, please try with the latest azure-cli.

**Closed by fengzhou-msft** 2020-10-24 09:53 UTC
Labels: Data Factory
